### ISSUE TITLE
repository in github steps

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#1]
While I seem to have successfully cloned the repository into github (although the last line "Checking connectivity" did not appear for mine), the commands following that we were given (cd myrepo; ls; less README.me) are all being met with the message that it's not recognized as an internal/external command, operable program, or batchfile. Maybe they're not supposed to be commands for the shell, but if they're not I don't understand where I should enter those commands..

@bensoltoff

**Comment by bensoltoff** [comment]
What operating system are you using? Windows or Mac?

**Comment by carlyoffidani** [comment]
windows

**Comment by bensoltoff** [comment]
Possibly its because there are some differences between the [command prompt](https://en.wikipedia.org/wiki/Cmd.exe) and the [shell](https://en.wikipedia.org/wiki/Unix_shell). Take a look at [this page](https://uc-cfss.github.io/shell.html) for more info on the shell and how to access it from a Windows machine via RStudio.

**Comment by carlyoffidani** [comment]
hmm.. I'm not sure what's happening. my apologies. I was using the shell from tools in rstudio. as I said, I had successfully cloned myrepo, but now it won't let me clone the same one again (which in retrospect is obvious since it was already created). However, I didn't know how to reenter that one.. so I cloned a new one ("myrealrepo"), but the same thing is happening...
![image](https://cloud.githubusercontent.com/assets/22498339/18923088/b2117386-8570-11e6-80a2-53246442a654.png)

**Comment by bensoltoff** [comment]
Change `my repo` to `myrealrepo`. You need to specify the name however you named it on Github. So

``` shell
git clone https://github.com/carlyoffidani/myrealrepo
cd myrealrepo
ls
less README.md
git remote show origin
```

And try using the shell from within RStudio. Command prompt in Windows uses a different command to list files (`dir`).
