### ISSUE TITLE
Combining repeated columns with distinct values

### ISSUE THREAD

**Issue by JordanAMartin** [uc-cfss/Discussion#11]
This is a very small version of a data frame that is actually 2,180 × 267. In the larger data frame, the last 256 variables are duplicates of 4 distinct AOIs. Here, I have cut it down to 2 duplicates of 2 AOIs. I would like my final table to have condensed all of the 256 into the 4 distinct columns. As you can see, the duplicate columns are only NULL values. How can I merge the duplicated columns and data while also preserving the relationship to the variables that precede the AOIs? I feel like my first roadblock is the fact that the duplicated variables have the same names throughout.

``` r
# A tibble: 20 × 7
   RecordingName SceneName FixationIndex `AOI[Screen]Hit` `AOI[Hand]Hit` `AOI[Screen]Hit` `AOI[Hand]Hit`
           <chr>     <chr>         <dbl>            <chr>          <chr>            <chr>          <chr>
1            M06     Fam 1             1                1              1             NULL           NULL
2            M06     Fam 1             2                1              0             NULL           NULL
3            M08     Fam 1             1                1              0             NULL           NULL
4            M08     Fam 1             2                1              1             NULL           NULL
5            M08     Fam 1             3                1              0             NULL           NULL
6            M08     Fam 1             4                1              0             NULL           NULL
7            M09     Fam 1             1                1              0             NULL           NULL
8            M09     Fam 1             2                1              0             NULL           NULL
9            M09     Fam 1             3                1              0             NULL           NULL
10           M06     Fam 2             1             NULL           NULL                1              1
11           M06     Fam 2             2             NULL           NULL                1              1
12           M06     Fam 2             3             NULL           NULL                1              1
13           M06     Fam 2             4             NULL           NULL                1              0
14           M08     Fam 2             1             NULL           NULL                1              0
15           M08     Fam 2             2             NULL           NULL                1              0
16           M08     Fam 2             3             NULL           NULL                1              0
17           M09     Fam 2             1             NULL           NULL                1              0
18           M09     Fam 2             2             NULL           NULL                1              0
19           M09     Fam 2             3             NULL           NULL                1              0
20           M09     Fam 2             4             NULL           NULL                1              0
```

**Comment by bensoltoff** [comment]
Can you attach the data file or point me to it on the internet? It's easier to import into R and test some code on it.

**Comment by bensoltoff** [comment]
This is quite a hack. The major problem is that `dplyr` doesn't like duplicated column names. You need to create unique names for each of the duplicated columns, then treat the problem like a gather + spread tidying assignment. Gather the variables of interest, remove missing values (i.e. all the `NULL`s in the original spreadsheet), then spread those values back into a single column for each variable.

``` r
library(readxl)
library(readr)
library(tidyverse)
library(feather)
library(stringr)

demoAOIfix <- read_excel("RawData/AOIFixationsM06-M14.xlsx")

# add number to end of duplicate column names
# - dplyr doesn't work with duplicate column names
names_demo <- colnames(demoAOIfix)
names_demo_unique <- duplicated(names_demo)

## only add number to duplicated columns
colnames(demoAOIfix) <- c(names_demo[names_demo_unique == FALSE],
  str_c(names_demo[names_demo_unique == TRUE], seq_along(names_demo[names_demo_unique == TRUE])))

demoAOIfix %>%
  # gather all of the variables of interest
  gather(Var, Val, -(StudioProjectName:GazeEventDuration)) %>%
  # remove extra number from variable
  # convert values to numbers, not characters
  mutate(Var = str_replace_all(Var, '[[:digit:]]+', ''),
         Val = as.numeric(Val)) %>%
  # remove rows with missing values
  na.omit() %>%
  # A few rows have multiple columns with values - I don't know what the data
  # actually means, so I just keep the first appearance of the observation. You
  # might want to do something different
  group_by(StudioProjectName, StudioTestName, RecordingName,
           RecordingDate, SceneName, SceneSegmentStart, SceneSegmentEnd,
           SceneSegmentDuration, RecordingTimestamp, FixationIndex, GazeEventDuration) %>%
  slice(1) %>%
  # spread the variables back into columns
  spread(Var, Val)
```

**Comment by JordanAMartin** [comment]
Can I use make.unique for the duplicated columns?

``` r
names(demoAOIfix) <- make.unique(names(demoAOIfix), sep = ".")
```

Will I have to repeat gather for all 64 versions of each AOI?

Will na.omit() count NULL as NA automatically?

**Comment by bensoltoff** [comment]
- I never heard of `make.unique()`, but it looks like that would be simpler
- You still need to gather + spread, because after `make.unique()` you still have 60+ versions of the columns. Gathering and then spreading will fix this because in the middle, you remove missing values
- No, `na.omit()` will not count `NULL` as missing. But by using the `as.numeric()` function, `NULL` values are converted to `NA`

**Comment by JordanAMartin** [comment]
But how do I specify to gather multiple variables by the same key?

**Comment by bensoltoff** [comment]
`gather(Var, Val, -(StudioProjectName:GazeEventDuration))` gathers all the duplicated columns (well, it gathers everything except the first ten variables, but it accomplishes the same task). I assumed the first 10 or so variables uniquely identify each observation. I honestly have no idea what this data actually represents.

If you look at the output after `gather()`, you can see multiple names are stored in `Var`. This tells us what variable is measured by `Val`.

**Comment by bensoltoff** [comment]
Try running the code, adding one line at a time. You can see how the final data frame takes shape.

**Comment by JordanAMartin** [comment]
Oh! I thought I have to replace Var with the variable names!

**Comment by bensoltoff** [comment]
Nope, the variable names are already in that column. Remember that's what gather does. It's just that here, you gather the columns but you need to perform another operation before the data is tidy.

**Comment by JordanAMartin** [comment]
Something strange is happening. I created a df of the Screen AOI to test how many rows minimum there should be (this is fixation gaze data from an eye tracker, so if AOI[Screen]Hit = 1, data is collected and thus, a row created). `df_screen` creates a table with 2179 rows (as does the code you provided). However, when I try to group and spread the `df_screen`, it creates a table with 2182 rows. 

``` r
df_screen <- select(demoAOIfix, Test, ID, Date, Trial, Start, End, TrialLength_ms, FixTime, FixationIndex, starts_with("AOI[Screen]Hit"))

df_screen_grouped <- df_screen %>%
  # gather all of the variables of interest
  gather(Var, Val, -(Test:FixationIndex)) %>%
  # remove extra number from variable
  mutate(Var = str_replace_all(Var, '.[:digit:]+', ''), Val = as.numeric(Val)) %>%
  # remove rows with missing values
  na.omit() %>%
  group_by(Test, ID, Trial, FixationIndex)
```

Somehow, 3 rows are being added. I don't know where or why.

Applying your code to the entire data set is producing even stranger output. When `Var` is spread, some `AOI[--]Hit` columns have `NA` values. When `Var` is spread, the `AOI[Screen]Hit` should have as many rows as there are values = 1. The other `AOI[--]Hit` columns should have value = 1 (indicating a fixation) or 0 (indicating another AOI has a fixation). 

I tweaked your code a bit, so here's the current pushed version:

``` r
# read data
demoAOIfix <- read_excel("RawData/AOIFixationsM06-M14.xlsx")
View(demoAOIfix)

# Make unique AOI names
names(demoAOIfix) <- make.unique(names(demoAOIfix), sep = ".")

# Drop variables I don't need
demoAOIfix <-select(demoAOIfix, -StudioProjectName, -GazeEventDuration)

# Rename ID variables
demoAOIfix <- rename(demoAOIfix, Test = StudioTestName, ID = RecordingName, Date = RecordingDate, Trial = SceneName, Start = SceneSegmentStart, End = SceneSegmentEnd, TrialLength_ms = SceneSegmentDuration, FixTime = RecordingTimestamp)
str(demoAOIfix)

# Gather each AOI
AOI_grouped <- demoAOIfix %>%
  # gather all of the variables of interest
  gather(Var, Val, -(Test:FixationIndex)) %>%
  # remove extra number from variable
  mutate(Var = str_replace_all(Var, '.[:digit:]+', ''), Val = as.numeric(Val)) %>%
  # remove rows with missing values
  na.omit() %>%
  # Group by ID and trial info
  group_by(Test, ID, Trial, FixationIndex) 
```

**Comment by bensoltoff** [comment]
``` r
> demoAOIfix %>%
+   # gather all of the variables of interest
+   gather(Var, Val, -(Test:FixationIndex)) %>%
+   # remove extra number from variable
+   mutate(Var = str_replace_all(Var, '.[:digit:]+', ''), Val = as.numeric(Val)) %>%
+   # remove rows with missing values
+   na.omit() %>%
+   # Group by ID and trial info
+   group_by(Test, ID, Trial, FixationIndex) %>%
+   mutate(n = n()) %>%
+   ungroup() %>%
+   arrange(-n, Test, ID, Date, Trial, Start, End, TrialLength_ms, FixTime, FixationIndex, Var)
# A tibble: 8,728 × 12
    Test    ID      Date  Trial  Start    End TrialLength_ms FixTime FixationIndex                Var   Val     n
   <chr> <chr>     <chr>  <chr>  <dbl>  <dbl>          <dbl>   <dbl>         <dbl>              <chr> <dbl> <int>
1  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21 AOI[Distracter]Hit     0     8
2  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21 AOI[Distracter]Hit     1     8
3  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21       AOI[Goal]Hit     1     8
4  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21       AOI[Goal]Hit     0     8
5  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21       AOI[Hand]Hit     0     8
6  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21       AOI[Hand]Hit     0     8
7  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21     AOI[Screen]Hit     1     8
8  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177466            21     AOI[Screen]Hit     1     8
9  Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177566            22 AOI[Distracter]Hit     0     8
10 Test1   M06 9/27/2016 Fam 12 168283 177899           9616  177566            22 AOI[Distracter]Hit     1     8
# ... with 8,718 more rows
```

My understanding is that for each observation, there should really only be 4 variables - Distractor, Goal, Hand, and Screen. `n()` tells us how many observed values there are for each observation. For the vast majority of observations, this is `4` as it is supposed to be. For three of your observations, two sets of duplicated columns have values filled (hence `n = 8`). One has a `0` and another has a `1`. When you try to `spread()` this data frame with the duplicates, you get an error because `tidyr` is trying to paste 2 values into the same cell.

`slice(1)` arbitrarily keeps just the first observed value from each variable. Since I have no way of knowing which is the correct value, that's how I solved the problem. It was only for three observations, so I wasn't concerned with potential bias introduced into the dataset. If you know of a better way to decide which values to keep, I encourage you to implement it.

**Comment by JordanAMartin** [comment]
Got it! I will try to figure that out. Thank you so much, this was incredibly helpful.
