### ISSUE TITLE
Error in install package 

### ISSUE THREAD

**Issue by Mirrorlkj** [uc-cfss/Discussion#111]
``` r
install.packages(c("socviz", "margins"))
#> Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
#>   cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
#> Warning: packages 'socviz', 'margins' are not available (for R version
#> 3.6.1)
#> Warning: unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.6:
#>   cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/PACKAGES'
```

<sup>Created on 2019-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bensoltoff** [comment]
Try again later. It looks like that CRAN server may be offline right now. You can also try to manually specify which server you download the packages from.

**Comment by Mirrorlkj** [comment]
> Try again later. It looks like that CRAN server may be offline right now. You can also try to manually specify which server you download the packages from.

How to specify server? 

I searched online and tried many ways and it turned out this line `options(download.file.method="libcurl")` works.. though I don't know how
