### ISSUE TITLE
No Git tab on RStudio

### ISSUE THREAD

**Issue by mabenavides** [uc-cfss/Discussion#112]
Hi, I'm working on my HW1, and using GitHub and RStudio (in the server), but apparently I'm doing something wrong. There is no Git Tab. Could you please point me in the right direction?  Thanks!

**Comment by bensoltoff** [comment]
Did you follow the instructions in the video to create a version controlled project? The tab should show up in the top right panel. There are other tabs there so be sure to look for the Git tab

**Comment by mabenavides** [comment]
I did. It didn't work at first, then, the tab appeared. Not sure how, but I'll add that to my HW hehe. Thanks!
