### ISSUE TITLE
Multiple Homework Submissions

### ISSUE THREAD

**Issue by kaymoorewms** [uc-cfss/Discussion#114]
I submitted my homework too quickly, as I was blindly following the (very helpful!) homework tutorial on the FAQ page. I now realize there are many things I didn't include, is there any way I can edit it? Am I allowed to submit another one or recommit? If this happens in the future (hopefully it won't because I will be more careful), will the most recent one be graded or do we only get the one submission?

**Comment by bensoltoff** [comment]
You can only have one open pull request at a time. If push additional requests while the pull request is open, they automatically are incorporated into the original submission.
