### ISSUE TITLE
Insert Image Into R Markdown

### ISSUE THREAD

**Issue by emma-badia** [uc-cfss/Discussion#115]
I've been having trouble putting an image into my homework. According to the Markdown cheat sheet, it looks like the correct format for displaying an image is ![caption](filename.extension). However, when I do this, a picture icon appears and the caption appears with a hyperlink, but if you click on it my browser opens a new tab as if the image file is a link to a website (and since the file name is not a valid link I get a 404 error). The image is a .png file saved to my desktop. 

I know the "()[]" format is for links, but I thought adding the exclamation point at the beginning specifies that what comes next is an image. Is there something I'm missing?

**Comment by bensoltoff** [comment]
You cannot use an image from the desktop. Otherwise no one else will see it. Instead, place the image in your `hw01` folder, stage and commit it. Then you can use the markdown syntax to put it in your document. So if the image is called `photo.png` the syntax would be `[My photo](photo.png)`

**Comment by emma-badia** [comment]
I see, thank you!
