### ISSUE TITLE
Issue cloning repository to local computer

### ISSUE THREAD

**Issue by nadiahwong** [uc-cfss/Discussion#117]
Hello! I have come across an issue with cloning which I think has something to do with how my terminal results are not matching up with what is shown in [Setup](https://cfss.uchicago.edu/setup/github/). 

When I put `git remote show origin` in my terminal, it is exactly the same as what is stated in the Setup, except for the last line, which shows:
`master pushes to master (fast-forwardable)`
when it is meant to be 
`master pushes to master (up to date)`
How do I change this?

This might be why I am unable to push anything to `myrepo`
@bensoltoff

**Comment by bensoltoff** [comment]
@nadiahwong are you using the RStudio Server? It is pre-installed with Git so it should not have any problems cloning the repo.

If you can attend my office hours today (link in Canvas) I strongly encourage it. We can try to troubleshoot it there.

**Comment by bensoltoff** [comment]
Though honestly that may not be an error or mistake. The message may have changed with more recent versions of Git. If you can successfully clone your fork of `hw01`, I wouldn't worry about that message
