### ISSUE TITLE
Errors with downloading rcfss

### ISSUE THREAD

**Issue by lbenrey** [uc-cfss/Discussion#118]
> devtools::install_github("uc-cfss/rcfss")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘cli’ 2.0.1 is already loaded, but >= 2.0.2 is required

**Comment by bensoltoff** [comment]
Try running `install.packages("cli")` first, then `devtools::install_github("uc-cfss/rcfss")`.

Or use the RStudio Server. `rcfss` is pre-installed there

**Comment by lbenrey** [comment]
it worked! Thank you.
