### ISSUE TITLE
coding a continuous variable into a categorical

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#12]
I am practicing with gundeaths for this homework, and wanted to create a few new variables for exploration.. however, I'm having trouble how to recode this season variable so it is it's own variable. 

data("gun_deaths")
gun_deaths
gun_deaths$season<-cut(gun_deaths$month, c(1,3,6,9,12), label = c(`winter`, `spring`, `summer`, `fall`))

this code was working when I wasn't trying to label the variables, but something is going wrong with the labels and it's giving me an error. I was looking on the different websites suggested when I had this question on homework 2, but there weren't any clear examples of how to relabel the continuous values into a string..

**Comment by bensoltoff** [comment]
You forgot to put your labels in quotation marks. As written, R thinks there is an object called `winter` you are attempting to refer to, when in fact `winter` does not exist. Instead you want the string `"winter"`

``` r
gun_deaths$season<-cut(gun_deaths$month,
                       c(1,3,6,9,12),
                       label = c("winter", "spring", "summer", "fall"))
```

**Comment by carlyoffidani** [comment]
Blast! I thought I was supposed to use the backticks for that.. Thanks!

**Comment by bensoltoff** [comment]
Nope. Use backticks in `tidyverse` functions when referring to columns that start with numbers or have spaces in their names. Otherwise use quotation marks to refer to strings.

**Comment by carlyoffidani** [comment]
Ok, so that worked while I was using the gun_deaths dataset from the library in R, but now that I am trying to use the downloaded dataset it is giving me trouble..

I know this is only somewhat related to the problem, but I'm trying to make sure I understand how to do this, and so far failing. In the imported data, the month column was coded as a character, so I tried to mutate it, which seemed to work. But then when I run the second half

data("gun_data")
gun_data %>%
mutate(month = as.numeric(gun_data$month))
gun_data$season<-cut(gun_data$month, c(0,3,6,9,12), label = c("winter", "spring", "summer", "fall")), I'm getting an error "Error in cut.default(gun_data$month, c(0, 3, 6, 9, 12), label = c("winter",  : 
  'x' must be numeric" 

why?

**Comment by bensoltoff** [comment]
Remember, the result of a piped operation is never saved into memory unless you explicitly save it. I also moved the `cut()` function into `mutate()` to be consistent about creating new columns.

``` r
data("gun_data")

gun_data <- gun_data %>%
  mutate(month = as.numeric(gun_data$month),
         season = cut(month, c(0,3,6,9,12), label = c("winter", "spring", "summer", "fall")))
```

This should work.
