### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by fernandoregalado** [uc-cfss/Discussion#120]
Prof. @bensoltoff, can we commint and push homeworks using Github Desktop? I found it more simple with less steps to follow but I wonder if same information as if were pushing directly from R is registered in the repository!

**Comment by bensoltoff** [comment]
You can if you want. The advantage to using Rstudio for managing Git is that everything is in a single application, but use what works for you. But I cannot guarantee our ability to troubleshoot problems related to that program.
