### ISSUE TITLE
Issue installing "devtools"

### ISSUE THREAD

**Issue by dmendieta99** [uc-cfss/Discussion#121]
I initially ran into this error as my user folder is "David's PC" and assumed the apostrophe was interfering. 

Error: unexpected string constant in:
"suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))
tools:::makeLazyLoading("devtools", "C:/Users/David'"

I changed the library where the packages would be installed, from the one found under my username folder (C:/Users/David's PC/Documents/R/win-library/3.6) to the one under Program Files (C:/Program Files/R/R-3.6.3/library/devtools), thinking that the location might have been the issue but ran into this error instead.

Error: unexpected string constant in:
"suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))
tools:::makeLazyLoading("devtools", "C:/Program Files/R/R-3.6.3/library/00LOCK-devtools/00new", keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = '"

I uninstalled R, R Studio, and Rtools thinking that it was a corruption issue but the issue continues to persist. I've been looking into changing the name of the folder "David's PC" but apparently doing so on Windows is a risky endeavor on its own.

**Comment by deblnia** [comment]
Some terminal stuff suggested [here ](https://stackoverflow.com/questions/31114991/installation-of-package-devtools-had-non-zero-exit-status-in-a-powerpc), but I'm not sure work best on your PC.
