### ISSUE TITLE
MACSS R Studio Not Working

### ISSUE THREAD

**Issue by j2jonathan952** [uc-cfss/Discussion#122]
Hi, I'm trying to finish up my homework, but the remote R Studio server stopped running any code and now it won't even load. I restarted my computer, reconnected to the VPN, and tried to reload the program, but it won't do anything. It says "unable to handle the request." Is anyone else having this problem?

**Comment by bensoltoff** [comment]
Yes, others have reported the same problem. I'll post any updates [here](https://github.com/cfss-sp20/hw02/issues/31)
