### ISSUE TITLE
Question about using the reorder function

### ISSUE THREAD

**Issue by tfhernandez** [uc-cfss/Discussion#123]
Hello! I was wondering if I could have a little help using the reorder function. Here is the line of code that I have been having trouble with:

ggplot(data = mass_shootings, aes(x = reorder(race, -n), y = n)) + geom_col() 

I have been receiving an error that says "Error: Mapping should be created with `aes() or `aes_()`". However, when I add "mapping=" then there is an error about an invalid unary operator (-n). Could you please help me use this reorder function correctly? (also, line of code follows counting race in the previous line)

**Comment by bensoltoff** [comment]
Are you piping into ggplot? If so you don't need to restate the data argument with the original data frame

**Comment by tfhernandez** [comment]
Thank you! Yes, I was so confused because I was accidentally redundant in the code.
