### ISSUE TITLE
Review of file submission process / how to view peer hwk files

### ISSUE THREAD

**Issue by reed-diana** [uc-cfss/Discussion#125]
I'm sure I missed this, but I'm not clear on how to tell which files to submit for a project. It looks like many of us (including me) submitted just one file for hw2, but some committed 11- including the graphs? Could we review instructions for this? I have read the course documentation and viewed the submission video, but I'm still not clear on how to know which files to submit.

Related to this, I'm not clear on how to view my peers' assignments on github. Do I need to download the files and open them in RStudio, or should I be able to view them directly (to get the graphs etc. to render?) Thanks

**Comment by deblnia** [comment]
Guideliens in re: which files to commit can be found [here](https://cfss.uchicago.edu/faq/homework-guidelines/#which-files-to-commit). Happy to answer more specific questions about that. 

In re: viewing assignments, if they've committed a .md file you should be able to view their submissions nicely in your browser. Just go to their repo (accessible by clicking [their_username:masterbranch] on their pull request) and click the .md file.

**Comment by nearridge** [comment]
Adding onto Deb's comment, in order to produce the .md file, you need to click the "knit" button in your RStudio session and commit the resulting files to your repo.

**Comment by nearridge** [comment]
If your peers have not committed .md files or their .md files are not up to date, I'd suggest cloning their repo and knitting/reviewing the code that way.
