### ISSUE TITLE
Peer Reviews - Not Assigned

### ISSUE THREAD

**Issue by j2jonathan952** [uc-cfss/Discussion#126]
I have not been assigned my classmates to review. It is probably because I submitted the assignment Tuesday rather than Monday. Do you know when I'll be assigned, so I can make sure to give feedback as soon as possible? @bensoltoff

**Comment by deblnia** [comment]
If you submitted after the assignment script was run, you likely won't be assigned. I think the general rule in this case is to just pick two submissions at random and peer-review them.

**Comment by j2jonathan952** [comment]
@deblnia thank you. In that case, I won't be reviewed though, right? Outside, of one of ya'll? I'll try and pick someone else who doesn't have any comments at the moment. How do you all know if I have done a review? I just want to make sure that it's easy for ya'll.

**Comment by deblnia** [comment]
Yes, unfortunately, I think you'll only get a review from a TA. In re: how we know if you've done the peer review, I believe we have another script that scrapes comments from all the pull requests (so so we'll know!) Don't worry!
