### ISSUE TITLE
Question about problem on the SCOTUS set

### ISSUE THREAD

**Issue by tfhernandez** [uc-cfss/Discussion#128]
Hello! I had a question about the Scalia problem in the third set of the homework. I started the question by trying to generate a bar graph with each bar as a year and two colors in each bar (one for 1 and 2) with the y-axis showing percent instead of frequency. However, I was having some problems with the scale, so I looked at the demo. I noticed that the demo takes a different approach and only shows when the outcome is the majority. Would it be better if I recode the variable as 0 and 1 and then try to find the average per year? I thought this might not be effective because it would then assign that average to each observation in that year? Thank you!

**Comment by bensoltoff** [comment]
That is what I did in the demo. Note that there are essentially 2 possible outcomes. Majority or minority. So the percentage of one outcome is 100 minus the percentage of the other outcome

**Comment by tfhernandez** [comment]
Thank you!
