### ISSUE TITLE
Question regarding HW3 scotus, the wording of last question

### ISSUE THREAD

**Issue by xumengyan01** [uc-cfss/Discussion#129]
I am a little confused about the wording of the last question in the "scotus" problem set. It asks: "In each term, how many of the term's published decisions (decided after oral arguments) were announced in a given month?" **What exactly do "published decisions (decided after oral arguments)" mean in the dataset?** 
I have looked into [codebook](http://scdb.wustl.edu/documentation.php?var=decisionType), specifically how "decisionType" is coded. I thought that the question was asking about cases where their "decisionType=1: Cases the Court decides by a signed opinion", but apparently these cases are not necessarily orally argued. (And when I filter on `decisionType == 1`, the sum is much larger than that in the demo.) Therefore, I wonder what conditions should be met to be counted as "published decisions (decided after oral arguments)" .
@bensoltoff Any detailed explanation or sources for me to consult would be much appreciated.

**Comment by deblnia** [comment]
I believe that published decisions includes per curiam opinions as well (i.e. `decisionType == 6` and `decisionType == 7`). If you look at the codebook, the description of those two refers back to `decisionType == 1`. Try filtering on those two as well?

**Comment by bensoltoff** [comment]
@xumengyan01 look at the [documentation for `decisionType`](http://scdb.wustl.edu/documentation.php?var=decisionType). At the bottom is a quick summary of all the possible values. That should indicate which decisions were published after oral arguments.
