### ISSUE TITLE
geom boxplot

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#13]
I am starting to try to model, following the book example of the nycflight data. However, several things are acting strange in my work so far... I've been trying to look and see the distribution of deaths by months of the year, and I wanted to use a boxplot. I tried a number of different ways to get the boxplot to compute without me adding a variable that counts the number of deaths in a month, but I kept getting error messages 

ggplot(data = gun_deaths) +
  geom_boxplot(mapping = aes(x = month))

Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1
In addition: Warning messages:
1: Continuous x aesthetic -- did you forget aes(group=...)? 
2: In is.na(data$y) :
  is.na() applied to non-(list or vector) of type 'NULL'

I tried specifying is.na as False, and it gave me a different error message..

then I tried to make a new dataframe with just the counts:

gun_deaths_month <- gun_deaths %>% 
  group_by(month) %>% 
  summarise(month_n = n())

ggplot(data = gun_deaths_month) +
  geom_boxplot(mapping = aes(x = month, y = month_n))

Warning message:
Continuous x aesthetic -- did you forget aes(group=...)?

and it doesn't print...

I feel like I'm just trying to follow the same exact protocol on the nycflight example, and I really don't know why it isn't working..

**Comment by bensoltoff** [comment]
Boxplots require two variables, an `x` and a `y`. What you want to graph is the frequency of each category in the variable `month`. What you want instead [is a bar chart](https://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf). With an extra line to add month labels to the graph, that would be

``` r
gun_deaths %>%
  mutate(month = factor(month, labels = month.abb)) %>%
  ggplot(aes(x = month)) +
  geom_bar()
```

The gun deaths data is not comparable to `nycflights` for this example. In that dataset, even after

``` r
daily <- flights %>% 
  mutate(date = make_date(year, month, day)) %>% 
  group_by(date) %>% 
  summarise(n = n())
daily
#> # A tibble: 365 × 2
#>         date     n
#>       <date> <int>
#> 1 2013-01-01   842
#> 2 2013-01-02   943
#> 3 2013-01-03   914
#> 4 2013-01-04   915
#> 5 2013-01-05   720
#> 6 2013-01-06   832
#> # ... with 359 more rows
```

there are multiple observations for each day of the week. But look at your output:

``` r
gun_deaths_month <- gun_deaths %>% 
  group_by(month) %>% 
  summarise(month_n = n())
gun_deaths_month
# A tibble: 12 × 2
   month month_n
   <dbl>   <int>
1      1    8273
2      2    7093
3      3    8289
4      4    8455
5      5    8669
6      6    8677
7      7    8989
8      8    8783
9      9    8508
10    10    8406
11    11    8243
12    12    8413
```

There is only one observation for each month. You cannot draw a boxplot when each category has just a single value.
