### ISSUE TITLE
Git not detected

### ISSUE THREAD

**Issue by eostrinidad** [uc-cfss/Discussion#137]
![Screen Shot 2020-06-22 at 10 56 21 AM](https://user-images.githubusercontent.com/67266504/85308745-35815e00-b477-11ea-8c6b-cdd2556ff2ba.png)

Hello! This appeared when I clicked on New Project - Version Control - Git .

**Comment by eostrinidad** [comment]
@bensoltoff, is this just me or do others have a similar experience?

**Comment by bensoltoff** [comment]
@bensoltoff yes we just discovered this. The server was reset over the weekend and it appears they forgot to configure Git 😭 

I'm contacting IT services to fix it ASAP

**Comment by eostrinidad** [comment]
@bensoltoff , thanks so much! :)

**Comment by bensoltoff** [comment]
@eostrinidad should be working now. Log off and back into the server and try again
