### ISSUE TITLE
Python: Conda Rout or Default

### ISSUE THREAD

**Issue by EmilyForden** [uc-cfss/Discussion#14]
I'm assuming I should just use the default python, not conda rout?

**Comment by bensoltoff** [comment]
What is "conda rout"? You should use the Anaconda distribution of Python, as the [setup instructions](https://uc-cfss.github.io/setup02.html) describe.

**Comment by EmilyForden** [comment]
I did, but when I went to open a new notebook, I was presented with two
options for Python (conda rout and default). I'll stick with default, since
the test worked just fine with it!
