### ISSUE TITLE
Unable to display image on Github

### ISSUE THREAD

**Issue by hanjimin06** [uc-cfss/Discussion#140]
I uploaded an image on the README using:

![Random Photo](Images/IMG_5383.JPG)

It appears fine locally, but whenever I go to my github page, if I click on the link I get sent to an error page instead of an image.

**Comment by wanitchayap** [comment]
When you embed the image, you don't need to provide the full path. The .md or .Rmd file will automatically assume you start from wherever that file is located. So you simply can do:
```
![caption](Images/IMG_5383.jpg)
```
given that the folder Images is in the same directory as your README.md, and the IMG_5383.jpg is in the Images folder. Also I don't see the Images folder as well as the jpg file itself on your github repo yet. Make sure you commit them or else the README.md won't be able to find the file!
