### ISSUE TITLE
os Sierra breaks git

### ISSUE THREAD

**Issue by JordanAMartin** [uc-cfss/Discussion#15]
After having done nothing other than install Anaconda, I can no longer create a version control project with git. The error tells me to specify its location if it is installed, but it is currently specifying the correct path.  I can waste time reinstalling git, but wondering why this might have happened in the first place.

**Comment by bensoltoff** [comment]
Did you close it because you fixed it?

**Comment by JordanAMartin** [comment]
I closed it because I recently update my osx, which maybe was the problem, and am redownloading git anyways.

**Comment by bensoltoff** [comment]
Okay, thanks

**Comment by JordanAMartin** [comment]
Nope, reinstalled and it still won't work.

**Comment by JordanAMartin** [comment]
Some folks have fixed this issue by downloading and installing Xcode 8 from the Mac store. But, that requires authorized access. Has anyone found a way around this?

**Comment by JordanAMartin** [comment]
If anyone has this problem in the future, this is how to fix it without downloading Xcode:

http://mac-how-to.wonderhowto.com/how-to/install-command-line-developer-tools-without-xcode-0168115/

**Comment by bensoltoff** [comment]
Thanks for the info! I still have to upgrade my Mac. I'll be sure to watch out for this issue
