### ISSUE TITLE
Repository not showing updated code after pushed to GitHub

### ISSUE THREAD

**Issue by emilyskyoung** [uc-cfss/Discussion#150]
I initially pushed to GitHub a version of my code but I found that it had a few errors. I went back to the original file in R and fixed the errors, and then pushed the new version (after committing it) to Github. However, when I look at my Github repository it is only showing the old version of the code and not the new one. Is there a reason that this might be happening?

**Comment by deblnia** [comment]
That definitely shouldn't be happening. What was the commit message on your final commit? Can you also try refreshing the GitHub page?

**Comment by emilyskyoung** [comment]
I actually kept working on it and found the problem - I had created two different repositories by accident and it was updating the wrong one. I think I've fixed it now but thank you for helping so quickly!
