### ISSUE TITLE
Pushing my changes on README file

### ISSUE THREAD

**Issue by javierfzs** [uc-cfss/Discussion#159]
I was wondering if you can help me with an issue with Homework 1:

After committing my name in my README file, I try to push this change to GitHub, and it appears this message: 
remote: Repository not found.
fatal: repository 'https://github.com/cfss-win21/hw01.git/' not found

I would like to know what is wrong.

Thanks

<img width="1046" alt="Screen Shot 2021-01-12 at 11 25 06 PM" src="https://user-images.githubusercontent.com/62916970/104406627-bd22dd00-552d-11eb-93ca-8c5f71014783.png">

**Comment by deblnia** [comment]
You appear to have cloned from the master, and not a fork. Try following [these steps](https://cfss.uchicago.edu/notes/common-git-problems/#accidentally-cloned-from-the-master-not-the-fork)!

**Comment by javierfzs** [comment]
Thanks! I solved the issue
