### ISSUE TITLE
Downloading cVPN

### ISSUE THREAD

**Issue by shiraaronson** [uc-cfss/Discussion#160]
I'm having trouble using the cVPN on my computer.

I followed the instructions on the UChicago website and downloaded the Cisco app, but when I try to log in it gives me the following message: "The application “Cisco AnyConnect Socket Filter” can’t be opened."

Does anyone know why that would be?

Thanks.

**Comment by bensoltoff** [comment]
Unfortunately I do not recognize that error message. The VPN is managed by the university. I recommend contacting [IT services](https://its.uchicago.edu/) to get support with that issue. We're more able to assist you with anything R/RStudio/Git related in this class.

**Comment by nearridge** [comment]
There a few possibilities that come to mind; also, let us know if this issue has persisted.

It might be that the application is not from an "authorized developer" and your computer is blocking you from opening it as a security issue. There should be an override in your Security settings for your computer. 

You might have downloaded the Windows version accidentally and are on MacOS (or vice versa).

**Comment by shiraaronson** [comment]
Thank you! I was able to sort it out with IT services this morning so I'm all good now!
