### ISSUE TITLE
Finding README.md file

### ISSUE THREAD

**Issue by Xinyi-Cai** [uc-cfss/Discussion#161]
I wonder anyone could help with this? 

In Using Git within Rstudio step2, I cannot find the README.md file in RStudio after all the previous steps. 
![截屏2021-01-14 下午10 15 18](https://user-images.githubusercontent.com/77372754/104602392-567cfb00-56b6-11eb-8898-3b46f2592aa2.png)

**Comment by bensoltoff** [comment]
When you created the repository on GitHub, did you make sure to check the box to [create a `README.md` file](https://cfss.uchicago.edu/setup/git-with-rstudio/#step-1-make-a-new-repo-on-github)? If you do not, then the repository will be completely empty on GitHub. The two files you see in the local folder right now are files created by RStudio when you cloned the repository to your computer.

If the file is not already present, you can just save a new text file called `README.md` in the repository, then stage and commit it.

**Comment by Xinyi-Cai** [comment]
Thank you! I have already solved that problem. But it seems that I have another problem that I cannot find the Git tab in the upper right pane even though I have already checked this..
![截屏2021-01-14 下午10 41 51](https://user-images.githubusercontent.com/77372754/104605799-e96b6480-56b9-11eb-8ccf-0d548b88414a.png)

**Comment by bensoltoff** [comment]
How did you clone the repository to your computer? It looks like you are correctly working in it as an [R project](https://r4ds.had.co.nz/workflow-projects.html), but on the computer the project folder is not also set up as a Git repository.

**Comment by Xinyi-Cai** [comment]
Problem solved. Thank you!
