### ISSUE TITLE
Getting File Not Found Error When Trying to Include Image From Local Computer

### ISSUE THREAD

**Issue by avivawaldman** [uc-cfss/Discussion#163]
I am trying to include an image from my local computer, having saved the images to a folder within the files tab in RStudio. The line I am trying to use is : ![My cat Moose](""Users/aviva/Documents/myrepo/homeworks/hw01/images/IMG_0369.jpg""). However, Markdown says that the resource path is not found. I got the file path directly from the "copy path" function of my computer, so I am confused as to why it is not working and would appreciate any help. Thank you!

**Comment by bensoltoff** [comment]
The format for a link is

```
![My cat Moose](location-of-file.jpg)
```

No need for quotation marks. Also you need to refer to the location of the file *relative to `README.md`*. So based on what I see in your post, it should look something like

```
![My cat Moose](images/IMG_0369.jpg)
```

**Comment by avivawaldman** [comment]
Thank you! That worked!
