### ISSUE TITLE
issues with editing the README.md file

### ISSUE THREAD

**Issue by sizhenf** [uc-cfss/Discussion#164]
Hi everyone,

After I forked the repo and cloned it to my computer, am I supposed to open the original README.md file in R studio and write in it or create and another README.Rmd and commit that? I'm not sure how to directly edit the README.md file, and if I can create another README.Rmd file, what am I supposed to do with the original README.md?

Thanks,
Serena

**Comment by deblnia** [comment]
Yes, open the original README and write in it! You should be able to open it by clicking the file name in your RStudio's "Files" pane (bottom right).

**Comment by sizhenf** [comment]
Got it! Thank you @deblnia 

Shall I close this issue?
