### ISSUE TITLE
Getting Error Message When I Try to Install Tidyverse Package

### ISSUE THREAD

**Issue by avivawaldman** [uc-cfss/Discussion#165]
Today when we were working on the exercises in class, I found that I could not open the tidyverse package on my local R installation, which I am using because every time I try to open the RStudio server I get a page not found error despite having installed the VPN software. I first installed the devtools package, which worked, and then when I tried to install the tidyverse package and open the library I got the error message : Error in install.packages : object 'tidyverse' not found, along with a warning that I did not have Rtools installed. I am not sure why it would not be working except that possibly it is a problem with my computer?

**Comment by bensoltoff** [comment]
Are you using a Mac or Windows machine? If you are on a windows machine, you probably need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) which is a separate application needed to install certain packages in R.

**Comment by avivawaldman** [comment]
That fixed it, thank you!
