### ISSUE TITLE
unable to assign reviewers to hw1 submission

### ISSUE THREAD

**Issue by sizhenf** [uc-cfss/Discussion#166]
Hi everyone,

As I learned from Tuesday's lecture, we ought to randomly pick 2 peer reviewers for our hw1 submission if we didn't get assigned any. It doesn't look like I have permission to do that. There's no little gear next to my reviewer column as shown in the image uploaded.

<img width="1301" alt="Screen Shot 2021-01-20 at 9 16 08 PM" src="https://user-images.githubusercontent.com/76606701/105181671-1068e100-5b67-11eb-9e16-b605931e1c52.png">

Also, I don't have any awaiting reviews either. Am I supposed to wait for people to assign me as their reviewers?

Best,
Serena

**Comment by bensoltoff** [comment]
For those who submit after the deadline, you do not have peer reviewers assigned to your pull request. Only a TA or myself will be assigned. Just leave comments on any two pull requests and we will count those for the week.

**Comment by sizhenf** [comment]
I see. Thank you Prof. Soltoff!

Thanks,
Serena
