### ISSUE TITLE
Error when downloading rcfss

### ISSUE THREAD

**Issue by sizhenf** [uc-cfss/Discussion#168]
Hi everyone,

I ran into this error message when trying to download rcfss from github.

**My Code**:
```
install.packages("tidyverse") # install tidyverse packages
library(tidyverse)            # load tidyverse packages, including ggplot2
library(knitr)                # load functions for formatting tables

# get data from rcfss package
# install latest version if not already installed
install.packages("devtools")       # install devtools
devtools::install_github("uc-cfss/rcfss")
library(rcfss)
```

Everything works fine until the command
```
devtools::install_github("uc-cfss/rcfss")
```

And the **error message** I got says 

```
> devtools::install_github("uc-cfss/rcfss")
Downloading GitHub repo uc-cfss/rcfss@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/uc-cfss/rcfss/tarball/HEAD' failed
```

I've tried both with and without a VPN so it's probably not a network issue. Any ideas on how might I solve this? 

Thanks!
Serena

**Comment by bensoltoff** [comment]
You should already have `rcfss` installed from the in-class assignments. You don't need to install it again as long as it is already present. As for that error, it might have been an issue accessing the GitHub server to download the package. Try again and see if it works now.

**Comment by sizhenf** [comment]
Thank you very much, Professor Soltoff!
