### ISSUE TITLE
example of modelbuilding using scorecard from the class website giving me a 404

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#17]
I was hoping to review examples of model building for the homework, but the link in the model-building week is broken... is it stored in another place?

thanks!

**Comment by bensoltoff** [comment]
Hmm. I'll look for the file when I get in the office tomorrow.

**Comment by bensoltoff** [comment]
It's located [here](https://uc-cfss.github.io/extras/cm007_scorecard_tutorial.html). I just fixed the link on the main site too
