### ISSUE TITLE
/bin/sh: There: command not found 

### ISSUE THREAD

**Issue by amymaldonado** [uc-cfss/Discussion#172]
I tried running this chunk of code within the .rmd file
```
white_count <- nrow(filter(mass_shootings, race == "White"))
white_count
```
And the result shows up as ```/bin/sh: There: command not found```
Everything prior to this chunk runs perfectly. It also runs just fine in the console. Why does this error occur and what should I do to fix it?

**Comment by bensoltoff** [comment]
Look inside the triple backticks on the first line of the code chunk. Inside the parentheses you should see the letter `r`. This tells the computer you are including R code in the chunk. If you omit that, the computer does not know what kind of code you are trying to write
