### ISSUE TITLE
hw03: vote variable

### ISSUE THREAD

**Issue by sizhenf** [uc-cfss/Discussion#175]
Hi everyone,

In 4 of part 2, we are asked to identify judges' agree-ness on cases. More specifically, "determine the ten justices who most and least frequently **agreed** with this outcome"

In answering this questions, I thought the variable of our interest is _vote_ in _scdb_vote_. However, when reading the [codebook](http://scdb.wustl.edu/documentation.php?var=vote), I'm a little confused about how this variable is coded. 

The vote variable takes 8 values:

1 | voted with majority or plurality
2 | dissent
3 | regular concurrence
4 | special concurrence
5 | judgment of the Court
6 | dissent from a denial or dismissal of certiorari, or dissent from summary affirmation of an appeal
7 | jurisdictional dissent
8 | justice participated in an equally divided vote

My **questions** are:

1. Am I looking at the right variable here?
2. If yes, would it be ok if I categorize (1, 3, 4) as **agree** and (2, 6, 7) as **dissent**? Then what 5 and 8? The codebook isn't super clear about their meanings..

Thanks,
Serena

**Comment by bensoltoff** [comment]
You might be able to use that variable, but I think it would be overly confusing. Why not just use the [`majority`](http://scdb.wustl.edu/documentation.php?var=majority) column?

**Comment by sizhenf** [comment]
Thanks Professor Soltoff!

**Comment by bensoltoff** [comment]
I'll leave this open in case other students have a similar question
