### ISSUE TITLE
Cant Knit

### ISSUE THREAD

**Issue by akerah** [uc-cfss/Discussion#176]
Tried to knit and I got this long scary notice 

*** caught segfault ***
address 0x68, cause 'memory not mapped'

Traceback:
 1: read_tokens_(data, tokenizer, col_specs, col_names, locale_,     n_max, progress)
 2: read_tokens(ds, tokenizer, spec$cols, names(spec$cols), locale_ = locale,     n_max = n_max, progress = progress)
 3: read_delimited(file, tokenizer, col_names = col_names, col_types = col_types,     locale = locale, skip = skip, skip_empty_rows = skip_empty_rows,     comment = comment, n_max = n_max, guess_max = guess_max,     progress = progress)
 4: read_csv("data/scdb-case.csv")
 5: eval(expr, envir, enclos)
 6: eval(expr, envir, enclos)
 7: withVisible(eval(expr, envir, enclos))
 8: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler,     error = eHandler, message = mHandler)
 9: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir,     enclos)), warning = wHandler, error = eHandler, message = mHandler))
10: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr,     envir, enclos)), warning = wHandler, error = eHandler, message = mHandler)))
11: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler, include_timing = include_timing)
12: evaluate::evaluate(...)
13: evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning),     keep_message = !isFALSE(options$message), stop_on_error = if (options$error &&         options$include) 0L else 2L, output_handler = knit_handlers(options$render,         options))
14: in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,     keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message),     stop_on_error = if (options$error && options$include) 0L else 2L,     output_handler = knit_handlers(options$render, options)))
15: block_exec(params)
16: call_block(x)
17: process_group.block(group)
18: process_group(group)
19: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),     error = function(e) {        setwd(wd)        cat(res, sep = "\n", file = output %n% "")        message("Quitting from lines ", paste(current_lines(i),             collapse = "-"), " (", knit_concord$get("infile"),             ") ")    })
20: process_file(text, output)
21: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
22: rmarkdown::render("/home/akerah/Mackey_github/hw03/scotus.Rmd",     encoding = "UTF-8", knit_root_dir = "~/Mackey_github/hw03")
An irrecoverable exception occurred. R is aborting now ...

**Comment by bensoltoff** [comment]
What happens if you run the code interactively in RStudio? Does it all run?
Looks like the issue is when you load one of the data files. It should be
near the top of your document.

**Comment by akerah** [comment]
My code runs in R, and my graphs appear. 

library(tidyverse)

This is how I loaded my data into my global environment

# load data
scdb_case <- read_csv("data/scdb-case.csv")
scdb_vote <- read_csv("data/scdb-vote.csv")
```

**Comment by bensoltoff** [comment]
You didn't mention this in office hours today. Have you resolved the error?

**Comment by akerah** [comment]
No, I was more concerned about fixing my graph when I came to OH.
