### ISSUE TITLE
Error in spark_connect()

### ISSUE THREAD

**Issue by bobaekang** [uc-cfss/Discussion#18]
I am trying the codes in today's class note now and having issues with the `spark_connect(master = "local", version = "2.0.0")` code. The error message I get is as follows:

```{r}
Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
  Failed to launch Spark shell. Ports file does not exist.
    Path: C:\Users\Bobae Kang\AppData\Local\rstudio\spark\Cache\spark-2.0.0-bin-hadoop2.7\bin\spark-submit.cmd
    Parameters: --class, sparklyr.Backend, --packages, "com.databricks:spark-csv_2.11:1.3.0","com.amazonaws:aws-java-sdk-pom:1.10.34", "C:\Users\Bobae Kang\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", C:\Users\BOBAEK~1\AppData\Local\Temp\Rtmpu0S3y2\file1a245ccb5c99.out
    
'C:\Users\Bobae' is not recognized as an internal or external command,
operable program or batch file.
```
Sorry to ask for a help right before the Thanksgiving Day, but it'd be really great if I can get some help remedying this issue.

Thank you and happy Thanksgiving!

**Comment by bensoltoff** [comment]
Did you run `spark_install(version = "2.0.0")` to install Spark on your computer? See [here](https://uc-cfss.github.io/distrib-comp_01.html#installation)

**Comment by bobaekang** [comment]
@bensoltoff 
Yes I did. It still gives me the same error message...

**Comment by bensoltoff** [comment]
Try installing `sparklyr` from the latest version on github

`devtools::install_github("rstudio/sparklyr")`

Then restart R and try again. Same error message?

**Comment by bensoltoff** [comment]
Also see [this about updating RStudio](http://spark.rstudio.com/#rstudio-ide)

**Comment by bobaekang** [comment]
@bensoltoff Using `devtools::install_github("rstudio/sparklyr")` solved the issue. Thank you very much!

**Comment by bensoltoff** [comment]
@uc-cfss/fa17 might be relevant to some of you with spark errors

**Comment by arthurzeyangyu** [comment]
What do you mean by relevant to some of you with spark error?

**Comment by bensoltoff** [comment]
If you get there error described in this issue then the solution might work for you

**Comment by arthurzeyangyu** [comment]
Oh, it says I need to download Java. Then, I download Java in my computer.
Then, I run the code again, it still doesn't work...
