### ISSUE TITLE
Can't fork

### ISSUE THREAD

**Issue by dipro-ray** [uc-cfss/Discussion#188]
The hw-01 repo on cfss-su21 seems to have forking disabled. I have tried cloning directly from cfss-su21, but am unable to push my work, probably because we cannot make changes to cfss-su21. Does forking need to be enabled or is this an issue on my end?

**Comment by bensoltoff** [comment]
Sorry, my bad. I forgot to go save when I enabled the forking setting. Yes you need to fork the repo, then make your changes there. You cannot push directly to the main repo since you do not own it.

**Comment by dipro-ray** [comment]
Got it, thanks!
