### ISSUE TITLE
Figuring out how to pull tweets from the past

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#19]
So I've been looking through the Tidy text mining book, through multiple blogs and searching online- many of the twitter analyses I'm seeing are people analyzing their own twitter archive over time, but they have easy access to that because they are able to simply download everything from their twitter account. what I'm struggling to figure out right now is how to adapt the twitter scraping code such that I can get a bigger archive, and search over a longer period of time. 

For example, if I am trying to search for the word immigrant and its use in tweets over the past year, is there a way I can specify dates in my code?  Like I said, I'm finding plenty of online examples for different analytics, but less varied examples for what can be extracted into data in the first place... 

tweets_immigrant<- searchTwitter('immigrant', n=10000)
df_immigrant <- twListToDF(tweets_immigrant) %>%
  tbl_df()
df_immigrant

**Comment by JordanAMartin** [comment]
Hey, in [HW07](https://github.com/JordanAMartin/hw07) I did a Twitter scrape in which I set dates. Twitter will limit your download rate such that you may be unable to pull a true sample of the day, rather you might just get all tweets that meet your criteria for the first 3 hours, depending on how many there were that day. I made a bunch of small sets and joined them in order to get truer sampling. Check [Load Data](https://github.com/JordanAMartin/hw07/blob/master/LoadData.R) to see how I got around it. BTW `library(beeper)` with `beep()` will let you walk away while it works!

**Comment by bensoltoff** [comment]
@JordanAMartin's solution may be your best hope. The Twitter API is designed to limit searches only to the most recent 7-10 days. It does not access the entire Twitter archive. I don't know of any easy or free way to access this larger archive, certainly not in time for the final project.

**Comment by futureofmaya** [comment]
Thanks for the help! I've been working on this: 

#twitter authentication
setup_twitter_oauth(consumer_key = getOption("twitter_api_key"),
                    consumer_secret = getOption("twitter_api_token"))

```r
dates <- tibble('2015-08-06','2015-08-07','2015-08-08', '2015-08-09','2015-08-10','2015-08-11','2015-08-12','2015-08-13','2015-08-14','2015-08-15','2015-08-16','2015-08-17', '2015-08-18', '2015-08-19','2015-08-20','2015-08-21','2015-08-22','2015-08-23','2015-08-24','2015-08-25','2015-08-26','2015-08-27','2015-08-28','2015-08-29','2015-08-30','2015-08-31',
           '2015-09-01','2015-09-02','2015-09-03','2015-09-04','2015-09-05','2015-09-06', '2015-09-07','2015-09-08','2015-09-09','2015-09-10','2015-09-11','2015-09-12','2015-09-13','2015-09-14','2015-09-15','2015-09-16','2015-09-17', '2015-09-18', '2015-09-19','2015-09-20','2015-09-21','2015-09-22','2015-09-23','2015-09-24','2015-09-25','2015-09-26','2015-09-27','2015-09-28','2015-09-29','2015-09-30',
           '2015-10-01','2015-10-02','2015-10-03','2015-10-04','2015-10-05','2015-10-06', '2015-10-07','2015-10-08','2015-10-09','2015-10-10','2015-10-11','2015-10-12','2015-10-13','2015-10-14','2015-10-15','2015-10-16','2015-10-17', '2015-10-18', '2015-10-19','2015-10-20','2015-10-21','2015-10-22','2015-10-23','2015-10-24','2015-10-25','2015-10-26','2015-10-27','2015-10-28','2015-10-29','2015-10-30','2015-10-31',
           '2015-11-01','2015-11-02','2015-11-03','2015-11-04','2015-11-05','2015-11-06', '2015-11-07','2015-11-08','2015-11-09','2015-11-10','2015-11-11','2015-11-12','2015-11-13','2015-11-14','2015-11-15','2015-11-16','2015-11-17', '2015-11-18', '2015-11-19','2015-11-20','2015-11-21','2015-11-22','2015-11-23','2015-11-24','2015-11-25','2015-11-26','2015-11-27','2015-11-28','2015-11-29','2015-11-30',
           '2015-12-01','2015-12-02','2015-12-03','2015-12-04','2015-12-05','2015-12-06', '2015-12-07','2015-12-08','2015-12-09','2015-12-10','2015-12-11','2015-12-12','2015-12-13','2015-12-14','2015-12-15','2015-12-16','2015-12-17', '2015-12-18', '2015-12-19','2015-12-20','2015-12-21','2015-12-22','2015-12-23','2015-12-24','2015-12-25','2015-12-26','2015-12-27','2015-12-28','2015-12-29','2015-12-30','2015-12-31',
           '2016-01-01','2016-01-02','2016-01-03','2016-01-04','2016-01-05','2016-01-06', '2016-01-07','2016-01-08','2016-01-09','2016-01-10','2016-01-11','2016-01-12','2016-01-13','2016-01-14','2016-01-15','2016-01-16','2016-01-17', '2016-01-18', '2016-01-19','2016-01-20','2016-01-21','2016-01-22','2016-01-23','2016-01-24','2016-01-25','2016-01-26','2016-01-27','2016-01-28','2016-01-29','2016-01-30','2016-01-31', 
           '2016-02-01','2016-02-02','2016-02-03','2016-02-04','2016-02-05','2016-02-06', '2016-02-07','2016-02-08','2016-02-09','2016-02-10','2016-02-11','2016-02-12','2016-02-13','2016-02-14','2016-02-15','2016-02-16','2016-02-17', '2016-02-18', '2016-02-19','2016-02-20','2016-02-21','2016-02-22','2016-02-23','2016-02-24','2016-02-25','2016-02-26','2016-02-27','2016-02-28','2016-02-29', 
           '2016-03-01','2016-03-02','2016-03-03','2016-03-04','2016-03-05','2016-03-06', '2016-03-07','2016-03-08','2016-03-09','2016-03-10','2016-03-11','2016-03-12','2016-03-13','2016-03-14','2016-03-15','2016-03-16','2016-03-17', '2016-03-18', '2016-03-19','2016-03-20','2016-03-21','2016-03-22','2016-03-23','2016-03-24','2016-03-25','2016-03-26','2016-03-27','2016-03-28','2016-03-29','2016-03-30','2016-03-31',
           '2016-04-01','2016-04-02','2016-04-03','2016-04-04','2016-04-05','2016-04-06', '2016-04-07','2016-04-08','2016-04-09','2016-04-10','2016-04-11','2016-04-12','2016-04-13','2016-04-14','2016-04-15','2016-04-16','2016-04-17', '2016-04-18', '2016-04-19','2016-04-20','2016-04-21','2016-04-22','2016-04-23','2016-04-24','2016-04-25','2016-04-26','2016-04-27','2016-04-28','2016-04-29','2016-04-30',
           '2016-05-01','2016-05-02','2016-05-03','2016-05-04','2016-05-05','2016-05-06', '2016-05-07','2016-05-08','2016-05-09','2016-05-10','2016-05-11','2016-05-12','2016-05-13','2016-05-14','2016-05-15','2016-05-16','2016-05-17', '2016-05-18', '2016-05-19','2016-05-20','2016-05-21','2016-05-22','2016-05-23','2016-05-24','2016-05-25','2016-05-26','2016-05-27','2016-05-28','2016-05-29','2016-05-30','2016-05-31',
           '2016-06-01','2016-06-02','2016-06-03','2016-06-04','2016-06-05','2016-06-06', '2016-06-07','2016-06-08','2016-06-09','2016-06-10','2016-06-11','2016-06-12','2016-06-13','2016-06-14','2016-06-15','2016-06-16','2016-06-17', '2016-06-18', '2016-06-19','2016-06-20','2016-06-21','2016-06-22','2016-06-23','2016-06-24','2016-06-25','2016-06-26','2016-06-27','2016-06-28','2016-06-29','2016-06-30',
           '2016-07-01','2016-07-02','2016-07-03','2016-07-04','2016-07-05','2016-07-06', '2016-07-07','2016-07-08','2016-07-09','2016-07-10','2016-07-11','2016-07-12','2016-07-13','2016-07-14','2016-07-15','2016-07-16','2016-07-17', '2016-07-18', '2016-07-19','2016-07-20','2016-07-21','2016-07-22','2016-07-23','2016-07-24','2016-07-25','2016-07-26','2016-07-27','2016-07-28','2016-07-29','2016-07-30','2016-07-31',
           '2016-08-01','2016-08-02','2016-08-03','2016-08-04','2016-08-05','2016-08-06', '2016-08-07','2016-08-08','2016-08-09','2016-08-10','2016-08-11','2016-08-12','2016-08-13','2016-08-14','2016-08-15','2016-08-16','2016-08-17', '2016-08-18', '2016-08-19','2016-08-20','2016-08-21','2016-08-22','2016-08-23','2016-08-24','2016-08-25','2016-08-26','2016-08-27','2016-08-28','2016-08-29','2016-08-30','2016-08-31',
           '2016-09-01','2016-09-02','2016-09-03','2016-09-04','2016-09-05','2016-09-06', '2016-09-07','2016-09-08','2016-09-09','2016-09-10','2016-09-11','2016-09-12','2016-09-13','2016-09-14','2016-09-15','2016-09-16','2016-09-17', '2016-09-18', '2016-09-19','2016-09-20','2016-09-21','2016-09-22','2016-09-23','2016-09-24','2016-09-25','2016-09-26','2016-09-27','2016-09-28','2016-09-29','2016-09-30',
           '2016-10-01','2016-10-02','2016-10-03','2016-10-04','2016-10-05','2016-10-06', '2016-10-07','2016-10-08','2016-10-09','2016-10-10','2016-10-11','2016-10-12','2016-10-13','2016-10-14','2016-10-15','2016-10-16','2016-10-17', '2016-10-18', '2016-10-19','2016-10-20','2016-10-21','2016-10-22','2016-10-23','2016-10-24','2016-10-25','2016-10-26','2016-10-27','2016-10-28','2016-10-29','2016-10-30','2016-10-31',
           '2016-11-01','2016-11-02','2016-11-03','2016-11-04','2016-11-05','2016-11-06', '2016-11-07','2016-11-08','2016-11-09','2016-11-10','2016-11-11','2016-11-12','2016-11-13','2016-11-14','2016-11-15','2016-11-16','2016-11-17', '2016-11-18', '2016-11-19','2016-11-20','2016-11-21','2016-11-22','2016-11-23','2016-11-24','2016-11-25','2016-11-26','2016-11-27','2016-11-28','2016-11-29')
 

dates_formatted <- as.Date(dates, format = "%YYYY-%mm-%dd")          

# getting the tweets
GetTweets <- function() {
  for (i in seq_along(dates_formatted)) {
    tweets <- searchTwitter('immigrant | immigration & -RT', 
                                 n=1000, lang='en',  
                                 since= "i")
    tweets <- strip_retweets(tweets, strip_manual = TRUE, strip_mt = TRUE)
    tweets<- twListToDF(tweets) %>%
      tbl_df
    }
  }
```

Problems include: 
1. I first tried to do this without the dates_formatted bit, and got this error from trying to run the GetTweets function: 
 Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format 
2. So I figured I should add in the as.Date part, but that gave me this error: 
Error in as.Date.default(dates, format = "%YYYY-%mm-%dd") : 
  do not know how to convert 'dates' to class “Date”

So... I don't know. Something I'm doing is quite wrong.

**Comment by bensoltoff** [comment]
```r
    tweets <- searchTwitter('immigrant | immigration & -RT', 
                                 n=1000, lang='en',  
                                 since= "i")
```

Change `since = "i"` to `dates[i]`. You are iterating over a series of numbers 1,2,3,4... so you need to refer to the index `[]` for `dates`. Alternatively, write the loop as

```r
  for (date in dates) {
    tweets <- searchTwitter('immigrant | immigration & -RT', 
                                 n=1000, lang='en',  
                                 since= date)
    tweets <- strip_retweets(tweets, strip_manual = TRUE, strip_mt = TRUE)
    tweets<- twListToDF(tweets) %>%
      tbl_df
    }
```

Make sure you are storing the tweets from each search in it's own object. Either in a list `vector("list", length(dates))` or appending the results from each search to a master data frame. As written right now all your search results are being overwritten each time the loop moves to the next iteration.

**Comment by carlyoffidani** [comment]
Whelp, having one embarassing problem, while trying to figure out what you mean by this last comment. So, I was going to take a guess at how to insert the vector code you listed, like this:


for (date in dates) {
  tweets <- vector("list", length(dates)) %>%
    searchTwitter('immigrant | immigration & -RT', 
                          n=1000, lang='en',  
                          since= date)
  tweets <- strip_retweets(tweets, strip_manual = TRUE, strip_mt = TRUE)
  tweets<- twListToDF(tweets) %>%
    tbl_df
}

which I was crossing my fingers would work, but a bit skeptical.. but before this I hit a roadblock with the dates, which I have certainly hit more than 15 minutes trying to figure out. when I use the same code as above:

dates <- tibble('2015-08-06','2015-08-07','2015-08-08', '2015-08-09','2015-08-10','2015-08-11','2015-08-12','2015-08-13','2015-08-14','2015-08-15','2015-08-16','2015-08-17', '2015-08-18', '2015-08-19','2015-08-20','2015-08-21','2015-08-22','2015-08-23','2015-08-24','2015-08-25','2015-08-26','2015-08-27','2015-08-28','2015-08-29','2015-08-30','2015-08-31',
                '2015-09-01','2015-09-02','2015-09-03','2015-09-04','2015-09-05','2015-09-06', '2015-09-07','2015-09-08','2015-09-09','2015-09-10','2015-09-11','2015-09-12','2015-09-13','2015-09-14','2015-09-15','2015-09-16','2015-09-17', '2015-09-18', '2015-09-19','2015-09-20','2015-09-21','2015-09-22','2015-09-23','2015-09-24','2015-09-25','2015-09-26','2015-09-27','2015-09-28','2015-09-29','2015-09-30',
                '2015-10-01','2015-10-02','2015-10-03','2015-10-04','2015-10-05','2015-10-06', '2015-10-07','2015-10-08','2015-10-09','2015-10-10','2015-10-11','2015-10-12','2015-10-13','2015-10-14','2015-10-15','2015-10-16','2015-10-17', '2015-10-18', '2015-10-19','2015-10-20','2015-10-21','2015-10-22','2015-10-23','2015-10-24','2015-10-25','2015-10-26','2015-10-27','2015-10-28','2015-10-29','2015-10-30','2015-10-31',
                '2015-11-01','2015-11-02','2015-11-03','2015-11-04','2015-11-05','2015-11-06', '2015-11-07','2015-11-08','2015-11-09','2015-11-10','2015-11-11','2015-11-12','2015-11-13','2015-11-14','2015-11-15','2015-11-16','2015-11-17', '2015-11-18', '2015-11-19','2015-11-20','2015-11-21','2015-11-22','2015-11-23','2015-11-24','2015-11-25','2015-11-26','2015-11-27','2015-11-28','2015-11-29','2015-11-30',
                '2015-12-01','2015-12-02','2015-12-03','2015-12-04','2015-12-05','2015-12-06', '2015-12-07','2015-12-08','2015-12-09','2015-12-10','2015-12-11','2015-12-12','2015-12-13','2015-12-14','2015-12-15','2015-12-16','2015-12-17', '2015-12-18', '2015-12-19','2015-12-20','2015-12-21','2015-12-22','2015-12-23','2015-12-24','2015-12-25','2015-12-26','2015-12-27','2015-12-28','2015-12-29','2015-12-30','2015-12-31',
                '2016-01-01','2016-01-02','2016-01-03','2016-01-04','2016-01-05','2016-01-06', '2016-01-07','2016-01-08','2016-01-09','2016-01-10','2016-01-11','2016-01-12','2016-01-13','2016-01-14','2016-01-15','2016-01-16','2016-01-17', '2016-01-18', '2016-01-19','2016-01-20','2016-01-21','2016-01-22','2016-01-23','2016-01-24','2016-01-25','2016-01-26','2016-01-27','2016-01-28','2016-01-29','2016-01-30','2016-01-31', 
                '2016-02-01','2016-02-02','2016-02-03','2016-02-04','2016-02-05','2016-02-06', '2016-02-07','2016-02-08','2016-02-09','2016-02-10','2016-02-11','2016-02-12','2016-02-13','2016-02-14','2016-02-15','2016-02-16','2016-02-17', '2016-02-18', '2016-02-19','2016-02-20','2016-02-21','2016-02-22','2016-02-23','2016-02-24','2016-02-25','2016-02-26','2016-02-27','2016-02-28','2016-02-29', 
                '2016-03-01','2016-03-02','2016-03-03','2016-03-04','2016-03-05','2016-03-06', '2016-03-07','2016-03-08','2016-03-09','2016-03-10','2016-03-11','2016-03-12','2016-03-13','2016-03-14','2016-03-15','2016-03-16','2016-03-17', '2016-03-18', '2016-03-19','2016-03-20','2016-03-21','2016-03-22','2016-03-23','2016-03-24','2016-03-25','2016-03-26','2016-03-27','2016-03-28','2016-03-29','2016-03-30','2016-03-31',
                '2016-04-01','2016-04-02','2016-04-03','2016-04-04','2016-04-05','2016-04-06', '2016-04-07','2016-04-08','2016-04-09','2016-04-10','2016-04-11','2016-04-12','2016-04-13','2016-04-14','2016-04-15','2016-04-16','2016-04-17', '2016-04-18', '2016-04-19','2016-04-20','2016-04-21','2016-04-22','2016-04-23','2016-04-24','2016-04-25','2016-04-26','2016-04-27','2016-04-28','2016-04-29','2016-04-30',
                '2016-05-01','2016-05-02','2016-05-03','2016-05-04','2016-05-05','2016-05-06', '2016-05-07','2016-05-08','2016-05-09','2016-05-10','2016-05-11','2016-05-12','2016-05-13','2016-05-14','2016-05-15','2016-05-16','2016-05-17', '2016-05-18', '2016-05-19','2016-05-20','2016-05-21','2016-05-22','2016-05-23','2016-05-24','2016-05-25','2016-05-26','2016-05-27','2016-05-28','2016-05-29','2016-05-30','2016-05-31',
                '2016-06-01','2016-06-02','2016-06-03','2016-06-04','2016-06-05','2016-06-06', '2016-06-07','2016-06-08','2016-06-09','2016-06-10','2016-06-11','2016-06-12','2016-06-13','2016-06-14','2016-06-15','2016-06-16','2016-06-17', '2016-06-18', '2016-06-19','2016-06-20','2016-06-21','2016-06-22','2016-06-23','2016-06-24','2016-06-25','2016-06-26','2016-06-27','2016-06-28','2016-06-29','2016-06-30',
                '2016-07-01','2016-07-02','2016-07-03','2016-07-04','2016-07-05','2016-07-06', '2016-07-07','2016-07-08','2016-07-09','2016-07-10','2016-07-11','2016-07-12','2016-07-13','2016-07-14','2016-07-15','2016-07-16','2016-07-17', '2016-07-18', '2016-07-19','2016-07-20','2016-07-21','2016-07-22','2016-07-23','2016-07-24','2016-07-25','2016-07-26','2016-07-27','2016-07-28','2016-07-29','2016-07-30','2016-07-31',
                '2016-08-01','2016-08-02','2016-08-03','2016-08-04','2016-08-05','2016-08-06', '2016-08-07','2016-08-08','2016-08-09','2016-08-10','2016-08-11','2016-08-12','2016-08-13','2016-08-14','2016-08-15','2016-08-16','2016-08-17', '2016-08-18', '2016-08-19','2016-08-20','2016-08-21','2016-08-22','2016-08-23','2016-08-24','2016-08-25','2016-08-26','2016-08-27','2016-08-28','2016-08-29','2016-08-30','2016-08-31',
                '2016-09-01','2016-09-02','2016-09-03','2016-09-04','2016-09-05','2016-09-06', '2016-09-07','2016-09-08','2016-09-09','2016-09-10','2016-09-11','2016-09-12','2016-09-13','2016-09-14','2016-09-15','2016-09-16','2016-09-17', '2016-09-18', '2016-09-19','2016-09-20','2016-09-21','2016-09-22','2016-09-23','2016-09-24','2016-09-25','2016-09-26','2016-09-27','2016-09-28','2016-09-29','2016-09-30',
                '2016-10-01','2016-10-02','2016-10-03','2016-10-04','2016-10-05','2016-10-06', '2016-10-07','2016-10-08','2016-10-09','2016-10-10','2016-10-11','2016-10-12','2016-10-13','2016-10-14','2016-10-15','2016-10-16','2016-10-17', '2016-10-18', '2016-10-19','2016-10-20','2016-10-21','2016-10-22','2016-10-23','2016-10-24','2016-10-25','2016-10-26','2016-10-27','2016-10-28','2016-10-29','2016-10-30','2016-10-31',
                '2016-11-01','2016-11-02','2016-11-03','2016-11-04','2016-11-05','2016-11-06', '2016-11-07','2016-11-08','2016-11-09','2016-11-10','2016-11-11','2016-11-12','2016-11-13','2016-11-14','2016-11-15','2016-11-16','2016-11-17', '2016-11-18', '2016-11-19','2016-11-20','2016-11-21','2016-11-22','2016-11-23','2016-11-24','2016-11-25','2016-11-26','2016-11-27','2016-11-28','2016-11-29')


dates_formatted <- as.Date(dates, format = "%YYYY-%mm-%dd")          

I'm getting the error message: Error in as.Date.default(dates, format = "%YYYY-%mm-%dd") : 
  do not know how to convert 'dates' to class “Date”
I double checked and it looks like as.Date is from base R. I also have pretty much every library/package loaded.. so I can't figure out what's going wrong.

**Comment by bensoltoff** [comment]
```r
library(tidyverse)
library(twitteR)

#twitter authentication
setup_twitter_oauth(consumer_key = getOption("twitter_api_key"),
                    consumer_secret = getOption("twitter_api_token"))

# set the sequence of dates to search over
dates <- c('2015-08-06','2015-08-07')
# dates <- seq(as.Date("2015-08-06"), as.Date("2016-11-29"), by = "day")

# create a list to store the tweets
tweets <- vector("list", length(dates))

# use a for loop to run the immigration search starting on each date
for(i in seq_along(dates)) {
  tweets[[i]] <- searchTwitter('immigrant | immigration & -RT', 
                               n=1000, lang='en',  
                               since= dates[i]) %>%
    strip_retweets(strip_manual = TRUE, strip_mt = TRUE) %>%
    twListToDF() %>%
    tbl_df
}

# collapse tweets into a single data frame
tweets_joined <- bind_rows(tweets) %>%
  # remove duplicate tweets that were retrieved in multiple searches
  unique()
str(tweets_joined)
```

```
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1015 obs. of  16 variables:
 $ text         : chr  "Trump just picked an immigrant for his Cabinet https://t.co/qIC8H7029n https://t.co/p6Ew4MDCmW" "The Ohio State Terrorist Saw Himself as a Victim of Islamophobia https://t.co/mniNPOQkLR via @NRO" "Five questions about Donald Trump's immigration plans https://t.co/ki9QHffflm via @WSJPolitics" "@PlungeMyClunge @BeastInTheHead The first word an immigrant vagina learns is \"fine\"" ...
 $ favorited    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ favoriteCount: num  0 0 0 0 0 0 0 0 0 0 ...
 $ replyToSN    : chr  NA NA NA "PlungeMyClunge" ...
 $ created      : POSIXct, format: "2016-11-30 15:38:53" "2016-11-30 15:38:43" "2016-11-30 15:38:41" ...
 $ truncated    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ replyToSID   : chr  NA NA NA "803985242231046144" ...
 $ id           : chr  "803986665928851465" "803986624635748352" "803986615454597120" "803986615035133952" ...
 $ replyToUID   : chr  NA NA NA "48612072" ...
 $ statusSource : chr  "<a href=\"http://www.crowdfireapp.com\" rel=\"nofollow\">Crowdfire App</a>" "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>" "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>" "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>" ...
 $ screenName   : chr  "SNIPER1776" "doubledittos" "maconserv" "Maxaretunit" ...
 $ retweetCount : num  0 0 0 0 0 0 0 0 0 0 ...
 $ isRetweet    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ retweeted    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ longitude    : chr  NA NA NA NA ...
 $ latitude     : chr  NA NA NA NA ...
```

This code will do what you want. Some tweaks I made:

1. I used the `seq` function to create the sequence of dates to search over, rather than hard coding that extremely long vector. It is currently commented out - test the script over just those first two dates. If it works, then you can remove the comment and run it for the full search window. Keep in mind that it took me about 30 seconds to search over the first two dates, so your script may take a very long time to run.
1. I store the output of each search in a list called `tweets` that I defined outside of the `for` loop. Each time I iterate through the dates, the results get stored in the next element of the list.
1. I use `bind_rows()` to collapse the list into a single data frame. Because multiple searches may retrieve the same tweets, I use the `unique()` function to filter out duplicated tweets.

**Comment by futureofmaya** [comment]
The code (THANK YOU) works for the two days, but when I try to run it for everything else, I get this error: 

Error in strsplit(since, " ") : non-character argument

I'm pretty confused, since the code doesn't even use the strsplit function. It seems to be originating from the loop. I looked to see if there was an extra space somewhere, which this seems to imply (maybe?) but can't find one. Not even sure which function is causing the issue, so I've been having trouble looking it up.

**Comment by bensoltoff** [comment]
Change the `dates` code to

```r
dates <- seq(as.Date("2015-08-06"), as.Date("2016-11-29"), by = "day") %>%
  as.character()
```

This makes sure `dates` is a character vector that can be used in the loop.

**Comment by futureofmaya** [comment]
Thank you for saving us yet again.

**Comment by futureofmaya** [comment]
And... another issue. Does this mean Twitter isn't happy about this whole thing? Should we try it in smaller chunks?

[1] "Rate limited .... blocking for a minute and retrying up to 119 times ..."
[1] "Rate limited .... blocking for a minute and retrying up to 118 times ..."
[1] "Rate limited .... blocking for a minute and retrying up to 117 times ..."
[1] "Rate limited .... blocking for a minute and retrying up to 116 times ..."

**Comment by bensoltoff** [comment]
Yes. Talk to @jordanamartin it sounds like she did something similar

**Comment by JordanAMartin** [comment]
@futureofmaya That's why I made the small query sets and joined them together. Based on my search parameters, I had to limit each query to a "mm/dd/yyyy to mm/dd+1/yyyy" span.
