### ISSUE TITLE
Getting a "skipping install..." message when trying to install rcfss

### ISSUE THREAD

**Issue by MedhaRaju** [uc-cfss/Discussion#197]
I'm trying to install rcfss using the following code:

if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}

devtools::install_github("uc-cfss/rcfss") 

When I run the above code, I get the following message:

Skipping install of 'rcfss' from a github remote, the SHA1 (5b60f614) has not changed since last install.
  Use `force = TRUE` to force installation
install.packages()

I tried typing force = TRUE, but that just generates the following message again:
install.packages()

How can I proceed to access the dataset in hw02?

**Comment by MedhaRaju** [comment]
I checked on Stackoverflow -- looks like this is not an "issue" per se, this seems to be the default behavior. I was able to access the dataset.

**Comment by bensoltoff** [comment]
Yes you only need to install the package if it is not already available.

**Comment by MedhaRaju** [comment]
Thank you!
