### ISSUE TITLE
Issues of drawing two graphs in hw2 using R

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#201]
How can I set the y-axis like this in R code? They are of unequal length
![WechatIMG48](https://user-images.githubusercontent.com/107418876/174501975-1ee8b932-fa9a-456e-b7a3-4c75831fb81a.jpeg)
?

How can I using facet_wrap while setting different binwidth for each graph in this pic
![501655674993_ pic](https://user-images.githubusercontent.com/107418876/174502008-30dd3d15-df50-43fe-be95-3dfb483908d9.jpg)
? @bensoltoff

**Comment by BaichenTan** [comment]
I figured out that the first graph requires us to rescale the yaxis in log scale, adding the function scale_y_continuous() to our codes, but I am still confused of how we can make the second graph by using facet_wrap, what other functions should we use to set different binwidth for each sub-graph?
Currently I create three distinct pictures and use ggarange to combine the three graphs into one graph, but I think that method is quite tedious so I thought there will be a simple way (just using facet_wrap) to realize this result.

**Comment by bensoltoff** [comment]
For the second graph, you can do it in a single plot with faceting. The binwidth had not changed between each of the panels. Instead the range of the x axis has changed between each panel. Look at the documentation for `facet_wrap()` and see what argument allows you to vary the range of the x or y axes.
