### ISSUE TITLE
confusion of the last question

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#202]
In the demo solution, for the last very open questions, we are required to explore the relationship between location type and mental illness.
![7211655752854_ pic](https://user-images.githubusercontent.com/107418876/174666194-a812ea3e-ceab-4c59-bcf1-fa4181f3ed69.jpg)
 
While in the hw file, it asks the relationship between race and mental illness.
Does it mean it is ok to explore either race or location in our final submission?
![7221655752966_ pic](https://user-images.githubusercontent.com/107418876/174666390-c5b1f79d-6a23-4c4a-af4a-2620be845f18.jpg)
@bensoltoff

**Comment by bensoltoff** [comment]
See the first issue in the homework 2 repo. Use the location type variable.
