### ISSUE TITLE
problem solved

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#203]
Dear Prof.Soltoff,
I realized what my problem is. Previously I thought faa and the abbreviations of airports, e.g. "LAX," are two ways of representing an airport: one is a combination of 2 numbers and a letter and the other is a combination of three letters. In other words, I thought for example LAX also has a 2-number-1-letter way of representation, like 08F or whatsoever. So that's why I am confused of how R can identifies how to match two number+1 letter combination with 3-letter combination. But then I use View() too see the airport table and realized that "LAX" is also a value of faa number. It's just some airports uses 2 number and a letter to represent a faa number and some use three letters to represent a faa number. @bensoltoff

**Comment by bensoltoff** [comment]
Ah, yes that is a discrepancy. For some reason though that is how the FAA codes them. There might be a substantive reason but it really doesn't matter. They just need to be exactly the same in order for the match to be found.
