### ISSUE TITLE
questions on hw3

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#205]
I am a little bit confused of the part ## Recode variables as you find necessary, what does this mean? what does recode mean? Does it mean to use different join() methods to create different tables for uses? Or does it mean to simplify the names of the variables so that some of them may not be too long? @bensoltoff

**Comment by bensoltoff** [comment]
I would suggest if you need to record or adjust columns, do it once at the beginning of the file. Especially if you use the same variable repeatedly, it's easier to modify it once rather than for each exercise.
