### ISSUE TITLE
confusion on question "In each term, how many of the term’s published decisions (decided after oral arguments) were announced in a given month?"

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#207]
For this question, the demo solution prints the results in the order "October, November, ..., September," which is not the usual chronological order.
Do we also need to create the graph in this order? Or we can use the general "Jan, Feb, ..., Dec" order?

**Comment by bensoltoff** [comment]
Note the footnote in the assignment instructions. A term of the supreme court runs from October to September which matches the fiscal year, so for this viz it makes sense to sort it chronologically starting on October.
