### ISSUE TITLE
issue on question 4 of hw3

### ISSUE THREAD

**Issue by BaichenTan** [uc-cfss/Discussion#208]
I am so confused of why my code does not print the color graph but only returned black and white graph, I added the fill argument here but it is not processed somehow
![7341656266664_ pic](https://user-images.githubusercontent.com/107418876/175827900-600de595-b8ae-4cf5-8d31-e8bde2ca7523.jpg)
![7351656266674_ pic](https://user-images.githubusercontent.com/107418876/175827903-b3c7521b-6f02-4158-9d0b-e388a7b2c79f.jpg)
: @bensoltoff

**Comment by bensoltoff** [comment]
You defined `fill` as an argument to `ggplot()`. It should instead be an argument to `aes()` when you create the mappings.
