### ISSUE TITLE
word count error

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#21]
I am working on topic analysis from the data for our final project, but running into issues. I cleaned the data using models from class:

```r
reg <- "([^A-Za-z_\\d#@']|'(?![A-Za-z_\\d#@]))"
immigrant_tweets_words <- immigrant_immigration_tweets %>% 
  mutate(text = 
           str_replace_all(text, "https://t.co/[A-Za-z\\d]+|http://[A-Za-z\\d]+|&amp;|&lt;|&gt;|@[a-z,A-Z]*", "")) %>%
  unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]"))
```

but when I try to do a word count, am getting an error

```r
tweet_words_count <- immigrant_tweets_words %>%
  count(word, sort = TRUE) %>%
  arrange(desc(n))
 
tweet_words_count

Error in count(., word, sort = TRUE) : unused argument (sort = TRUE)
```

if I remove sort =TRUE, I get another error:

```
Error in UseMethod("as.quoted") : 
  no applicable method for 'as.quoted' applied to an object of class "function"
```

I am really not sure what's going on.. I looked up that error message, but it looks like it comes up for a number of issues, and the solutions I found didn't seem to apply to my problem..

**Comment by bensoltoff** [comment]
What does `immigrant_tweets_words` look like? Run `str(immigrant_tweets_words)` from the console and print the output here.

**Comment by futureofmaya** [comment]
We managed to figure this out, but stay tuned for probably a million other issues within the next few days!
