### ISSUE TITLE
Filtering Dates Using Shiny

### ISSUE THREAD

**Issue by futureofmaya** [uc-cfss/Discussion#23]
And... another one. 

I'm asking before I begin to write any code. Carly and I want to filter by date using Shiny. I know we worked with a package that did something with transforming dates before. First, what was that again (can't figure out where it was within everything we've done)? and second, would that help? I figured I might need to transform dates prior to inputting. Is there some obvious way to deal with the filtering? If not, I'll search around more; just figured I'd ask before I made up something that obviously wasn't going to work and spent like 97897 hours on it.

**Comment by futureofmaya** [comment]
Actually, never mind for now. I seem to have found documentation by figuring out what terms to Google. Again, will report back if I have issues.

**Comment by futureofmaya** [comment]
Ok I'm back already. I'm trying to get the dataframe into three columns: one with the date, one with the time, and one with the word. Eventually, I want to get it in the form where we could make a word cloud for a particular date interval. However, I'm trying to separate one column, which is currently the date and time, into two. I know there's an easy way to do this, but I can't remember where or what it is and can't seem to find it. Below is what I have. Here's, the first part, all of which works:  

```r
allthetweets <-read_csv("allthetweets.csv")
tweetswords <- allthetweets %>%
  select(text, created) 

tweetswords %>%
  head() %>%
  knitr::kable(caption = "Tweets with the word immigration")

reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))"

tweet_words <-tweetswords %>%
  filter(!str_detect(text, '^"')) %>%
  mutate(text = str_replace_all(text, "https://t.co/[A-Za-z\\d]+|&amp;", "")) %>%
  unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]")) 


tweet_words_count <- tweet_words %>%
  count(word, sort = TRUE) %>%
  arrange(desc(n))
```
And here's where I get into trouble. tweet_words is just the words and eliminates the created column. This, below, just gives me the created column separated into two. I need them all in one data frame! Ahhhhh!

```r
library(stringr)
tweet_dates <- str_split_fixed(tweet_words$created, " ", 2) 
```

**Comment by bensoltoff** [comment]
Because `count` creates a summary data frame - it will not have the same number of rows as the original table. Try the `separate` function from `tidyr` - it allows you to split a column into two. So it would be something like

```r
tweet_words %>%
  separate(created, into = c("date", "time"))
```

Though for filtering tweets based on a time interval, check out `lubridate` and the [R for Data Science book](http://r4ds.had.co.nz/dates-and-times.html).

**Comment by futureofmaya** [comment]
Thank you! That worked. I knew it was pretty obvious, but couldn't find it in R for Data Science and wasn't getting lubridate or separate to work on my own. Who knows why. 

So that was ok... now I'm trying to put it all in Shiny. I'm going to post my code below, but Carly and I are going to come in to office hours tomorrow. Feel free to ignore this until then. I think I'm just having trouble conceptualizing how to get it all into Shiny. 

```r
library(shiny)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(twitteR)
library(httpuv)
library(ggplot2)
library(scales)
library(readr)
library(tm)
library(stringr)
library(wordcloud)
library(knitr)
library(twitteR)
library(tidytext)
library(syuzhet)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr )
library(rtweet)
library(tidyverse)

allthetweets <-read_csv("allthetweets.csv")
tweetswords <- allthetweets %>%
  select(text, created) 

tweetswords %>%
  head() %>%
  knitr::kable(caption = "Tweets with the word immigration")

reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))"

tweet_words <-tweetswords %>%
  filter(!str_detect(text, '^"')) %>%
  mutate(text = str_replace_all(text, "https://t.co/[A-Za-z\\d]+|&amp;", "")) %>%
  unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]")) 

tweet_dates2 <- tweet_words %>%
  separate(created, into = c("date", "time"), sep = -9)

ui <- fluidPage(titlePanel("Tweeting Immigration"),
                sidebarLayout(
                  sidebarPanel(
                    dateRangeInput('dateRange',
                                   label = 'Date range input: yyyy-mm-dd',
                                   start = Sys.Date() - 2, end = Sys.Date() + 2
#this part definitely works
                    )
                  ),
                  mainPanel(plotOutput("daterange"),
                )))

server <- function(input, output) {
  filtered <- reactive({
    if(is.null(input$subtypeInput)) {
      return(NULL)
    }
    
  output$daterange <- renderPlot({
    if (is.null(filtered())) {
      return()
    }
    wordcloudAtXTime <- function(time1, time2) {
      time1= input$start
      time2= input$end
      starttime <- as.POSIXct("time1")
      endtime <- as.POSIXct("time2")
      forfunction <- tweet_dates2$date %>%
        filter(interval(starttime,endtime))
      tweet_words_count_function <- forfunction %>%
        count(word, sort = TRUE) %>%
        arrange(desc(n))
      ggplot(tweet_words_count_function[1:20,], aes(x= reorder(word, -n), y = n)) +
        geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE) + 
        coord_flip() +
        xlab("Number of Occurances") + ylab("Word") + ggtitle("Words Used in Tweets about Immigration")
      
  })
  
}

shinyApp(ui = ui, server = server)
```
