### ISSUE TITLE
Sentiment analysis issues: tracking over time and deeper explorations

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#24]
@futureofmaya

I am attaching the code we are working on for our sentiment analysis.. Although I have been able to look at sentiments over the period of time we are looking at and postive/negative sentiments over the time period, I have been struggling to figure out how to track changes in sentiment over time, the code that I have found of people doing this hasn't been working.. it keeps coming back with an error message, and while I have deduced it has something to do with the melt function, I haven't been able to figure out what exactly is going wrong with it. 

```r
immigrant_tweets_with_sentiment$month <- month(immigrant_tweets_with_sentiment$created, label = TRUE)
monthlysentiment <- immigrant_tweets_with_sentiment %>% group_by(month) %>% 
  summarise(anger = mean(anger), 
            anticipation = mean(anticipation), 
            disgust = mean(disgust), 
            fear = mean(fear), 
            joy = mean(joy), 
            sadness = mean(sadness), 
            surprise = mean(surprise), 
            trust = mean(trust)) %>% melt
names(monthlysentiment) <- c("month", "sentiment", "meanvalue")
```

the error message I'm getting is "No id variables; using all as measure variables"

I also tried: 

```r
posnegtime <- immigrant_tweets_with_sentiment %>% 
  group_by(created = cut(created, breaks="2 months")) %>%
  summarise(negative = mean(negative),
            positive = mean(positive)) %>% melt
names(immigrant_immigration_tweets) <- c("created", "sentiment", "meanvalue")
posnegtime$sentiment = factor(posnegtime$sentiment,levels(posnegtime$sentiment)[c(2,1)])
```

In addition, I know on my and Rita's homework you commented that in our sentiment analysis, when we see surprising results (Such as fear/trust being very close in frequency of sentiment), that we should explore this more deeply. However, we are not really sure how to explore this more- I am currently adapting code from the jane austen example from tidytextmining, to look at the particular words that are contributing most to sentiments of fear/joy, etc, but other than that we're not sure how to explore this further...

**Comment by bensoltoff** [comment]
You could consider the change over time simply as the difference in average sentiment in month `t` compared to month `t-1`. To do that, use the `lag` function like this:

```r
immigrant_tweets_with_sentiment$month <- month(immigrant_tweets_with_sentiment$created, label = TRUE)
monthlysentiment <- immigrant_tweets_with_sentiment %>%
  mutate(month = month(created, label = TRUE)) %>%
  group_by(month) %>% 
  summarise(anger = mean(anger), 
            anticipation = mean(anticipation), 
            disgust = mean(disgust), 
            fear = mean(fear), 
            joy = mean(joy), 
            sadness = mean(sadness), 
            surprise = mean(surprise), 
            trust = mean(trust)) %>%
  ungroup() %>%
  mutate(anger_change = anger - lag(anger))
```

Do that for each type of sentiment. Alternatively, depending on how many time periods `t` you have, you could use a [rolling average](https://en.wikipedia.org/wiki/Moving_average) using the `RcppRoll` library:

```r
install.packages(RcppRoll)
library(RcppRoll)

monthlysentiment %>%
  # calculate a rolling mean for anger using a 3 month time period
  mutate(roll_anger = roll_mean(anger, x = 3))

**Comment by bensoltoff** [comment]
As for your second question, you could explore quantitatively what words are most used for those sentiments and if there are any commonalities. More so what I would like to see is an effort to explain why the phenomenon occurred. Can you give me a reasonable explanation for those emotions being paired together? Even if you don't have the empirical evidence to back it up (though that would help), some conjecture would be useful.

**Comment by carlyoffidani** [comment]
Your second response makes sense, thanks.

Your first I am trying to figure out.. I am running the code (below), but my table is coming up with n/a values for the variables that are emotion_change. 

immigrant_tweets_with_sentiment$month <- month(immigrant_tweets_with_sentiment$created, label = TRUE)
monthlysentiment <- immigrant_tweets_with_sentiment %>%
  mutate(month = month(created, label = TRUE)) %>%
  group_by(month) %>% 
  summarise(anger = mean(anger), 
            anticipation = mean(anticipation), 
            disgust = mean(disgust), 
            fear = mean(fear), 
            joy = mean(joy), 
            sadness = mean(sadness), 
            surprise = mean(surprise), 
            trust = mean(trust)) %>%
  ungroup() %>%
  mutate(anger_change = anger - lag(anger)) %>%
  mutate(disgust_change = disgust - lag(disgust)) %>%
  mutate(fear_change = fear - lag(fear)) %>%
  mutate(joy_change = joy - lag(joy)) %>%
  mutate(sadness_change = sadness - lag(sadness)) %>%
  mutate(surprise_change = surprise - lag(surprise)) %>%
  mutate(trust_change = trust - lag(trust))


In addition, it looks like it's trying to calculate one bumber, rather than looking at the shifts over time. Maybe I'm wrong about that, but I still don't quite understand how, if I was able to generate those variables (For example trust_change), I would graph them over time..

**Comment by carlyoffidani** [comment]
*number

**Comment by carlyoffidani** [comment]
So, for example, if the mean had been sufiicient I was going to make a chart like this:

ggplot(data = monthlysentiment, aes(x = month, y = meanvalue, group = sentiment)) +
  geom_line(size = 2.5, alpha = 0.7, aes(color = sentiment)) +
  geom_point(size = 0.5) +
  ylim(0, NA) +
  theme(legend.title=element_blank(), axis.title.x = element_blank()) +
  ylab("Average sentiment score") + 
  ggtitle("Sentiment During the Year")

But I'm not sure how that would work with the lag..

**Comment by bensoltoff** [comment]
The lag would just show you the change from the previous month. If you just want a visualization, why not plot month by meanvalue and add `geom_smooth()`? That will give you a trend line indicating the pattern over time.
