### ISSUE TITLE
question about the shiny html incorporation into the whole web_site

### ISSUE THREAD

**Issue by jtbeyond** [uc-cfss/Discussion#28]
Hi, Dr Soltoff
   Yuhao and I are still working on the final part in out project: to render the whole website with one shiny html. However, we find although the rmd can run smoothly, it cannot correctly create a html file (we find there is a blank chunk in the shinny html), do you have any clue about this? Thank you so much. And we are sorry for submission the whole stuff late. 

Tong and Yuhao

PS: 
We have

title: "Interactive Ideological Analysis"
output: 
  html_document:
    theme: cosmo
runtime: shiny

as the front matter

Also, we have 

```{r Shiny, echo = FALSE, eval = TRUE} 
in the shiny app. 


@bensoltoff

**Comment by bensoltoff** [comment]
That won't work on GitHub pages because GitHub does not implement a shiny server. Build the app and put it in shiny apps.io, then link to it or embed it in your website.

**Comment by jtbeyond** [comment]
Thank you so much!

Best,
Tong
