### ISSUE TITLE
Can't Enter Password for myrepo

### ISSUE THREAD

**Issue by EmilyForden** [uc-cfss/Discussion#3]
I am still working my way through the installation and when I am prompted to enter my username and password for the practice readme file, it accepts my username but a key icon appears and I can't seem to enter my password. Any advice?

**Comment by bensoltoff** [comment]
@EmilyForden did you close the issue because you fixed the problem?

**Comment by EmilyForden** [comment]
I did!

**Comment by bensoltoff** [comment]
Great! Glad to hear you fixed it. In the future, when you close the issue just write a short comment explaining what you did to fix the problem (if another student has the same problem, this can be helpful information).
