### ISSUE TITLE
Question about boxplots

### ISSUE THREAD

**Issue by gmvelez** [uc-cfss/Discussion#30]
Hi!

When I try to do a boxplot with a discrete (0 or 1) x variable, it is doing something odd where it groups both possibilities into one.

Here is the code:

gun_deaths %>%
  ggplot(aes(x = police, y = age)) +
  geom_boxplot()

Which produces this:
[odd_plot.pdf](https://github.com/uc-cfss/Discussion/files/706861/odd_plot.pdf)

I know it has something with the fact that it is reading police as continuous, but I am not sure how to fix this.

Thank you!

**Comment by jmausolf** [comment]
Basically, you are correct. police is read as an integer, which you can tell with the function `typeof(variable_name)`. You may also want to make some other changes to this graph like adding a title, fixing axis labels, and value labels, but you will get the basic plot with a simple change to your code:

```r
library(tidyverse)
library(rcfss)

typeof(gun_deaths$police) #Shows you have an integer versus factor

gun_deaths <- gun_deaths %>%
  mutate(police = as.factor(police))
  
ggplot(data = gun_deaths, aes(x = police, y = age)) +
  geom_boxplot()
```

**Comment by gmvelez** [comment]
Thanks Josh!  That makes a lot of sense and helped me with a couple other graphs.
