### ISSUE TITLE
Question about changing column names

### ISSUE THREAD

**Issue by gmvelez** [uc-cfss/Discussion#32]
Hi Josh and Ben,

I was wondering how you can change column names when you have something that is not clean.  For example, if I am dealing with something like: Friday Lab Times (10-1, 2-11)

If I want to switch that to be just LabTimes, I was trying mutate with creating a new column to be LabTimes and setting it equal to "Friday Lab Times  (10-1, 2-11), but it is not recognizing that.

Thanks!

All the best,

Gabe

**Comment by bensoltoff** [comment]
Use the `rename()` function, but wrap the non-standard word in backticks (``). Like this

```r
rename(data_set, LabTimes = `Friday Lab Times (10-1, 2-11)`)
```
