### ISSUE TITLE
Question about how to do group_by or count and keep other data

### ISSUE THREAD

**Issue by gmvelez** [uc-cfss/Discussion#33]
Hi,

I am running into the issue of trying to figure out with the proportion questions how to do a count and get my proportion, but without losing another column I want to have for use later.  I can think of one way around it - saving it as a new dataset and then joining it with the original, but that seems more round about.

Thanks!

**Comment by bensoltoff** [comment]
Give us an example using the code you've developed so far. Makes it easier to visualize what you want to do

**Comment by gmvelez** [comment]
So, I have been using the following to get the proportion of conservative cases before then plotting it.  I am struggling now because I know I need the chief variable to facet_wrap, but it gets lost when I do the count.  

scdbv_hwvar %>%
  select(term, caseIssuesId, decisionDirection, chief) %>%
  unique() %>%
  count(term, decisionDirection) %>%
  ungroup() %>%
  complete(term, decisionDirection, fill = list(n=0)) %>%
  group_by(term) %>%
  mutate(total = sum(n), 
         proportion = n / total)  %>%
  filter(decisionDirection == "Conservative")

**Comment by bensoltoff** [comment]
Add `chief` as a variable in `count()`. Like

```r
scdbv_hwvar %>%
select(term, caseIssuesId, decisionDirection, chief) %>%
unique() %>%
count(term, decisionDirection, chief)
```

This makes each row of the summarized table a term-decisionDirection-chief observation and preserves the `chief` variable.

**Comment by gmvelez** [comment]
Thank you.

Now it makes sense to me.  I have been able to create the facet-grid ggplot with it, but I am having difficulty with coloring the line segments.  When I try to add chief as color, it isn't included in the graph (see code below).  I tried looking up line segment coloring, but couldn't find anything useful.  Is there a particular code for coloring line segments?

Code:

```r
 ggplot(aes(term, proportion), color = chief) +
  geom_line() +
  ggtitle("Percentage of Cases in Each Term Decided in Conservative Direction") +
  scale_y_continuous(name = "Percentage", labels = c("0%", "20%", "40%", "60%", "80%")) +
  xlab("Term Year")
```

**Comment by bensoltoff** [comment]
Because you are not adding `color = chief` in the correct function. You are adding it as a parameter for `ggplot()`, but remember that color is an **aesthetic** for the `geom_line()`. So you need to add it in the `aes()` function.

```r
ggplot(aes(term, proportion, color = chief)) +
  geom_line() +
  ggtitle("Percentage of Cases in Each Term Decided in Conservative Direction") +
  scale_y_continuous(name = "Percentage", labels = c("0%", "20%", "40%", "60%", "80%")) +
  xlab("Term Year")
```
