### ISSUE TITLE
How to use a single value in a data frame as a "value"?

### ISSUE THREAD

**Issue by WuyunpengChen** [uc-cfss/Discussion#38]
In the class exercise, there is one question about calculating the number of schools that have a lower cost than UChicago, and I try to solve this problem in the following way:
test1<-scorecard%>%
  filter(name=="University of Chicago")
aaa<-test1[c("cost")]
test0<-scorecard%>%
  filter(cost<aaa)

In expectation, I would get the value of cost of UChicago and store it in "aaa" and then use it as a filter to choose what school reach my requirement. However, such code will not work and the essential reason is "aaa" is a 1X1 data frame and you cannot make such logical comparison in this situation.
The value of aaa is 62425 and actually, if I replace aaa with 62425 in the previous code, it would work for logical comparison using a value rather than a data frame is acceptable.
The essential problem is because of aaa is not a pure value, so when you use it in a comparison, it would actually return the following outcome:
100<aaa
Cost
TRUE
or
1000000<aaa
Cost
False
There is always a column name Cost exist and because of this, the result could not be used in the filter.
So here comes the question, does anyone have any idea of using a single value in the data.frame as a single "value"?

==================================================================
The problem is successfully solved, and here is two way to write the code:
1. Thanks to Benjamin as he provided the easist way to improve the code:
test1<-scorecard%>%
  filter(name=="University of Chicago")
_#we got a 1 row data frame of UChicago_
aaa<-test1[c("cost")]
_#then we save the value of cost of UChicago in a separate data frame_
aaa<-aaa[[1]]
_#we then get the first (and the only) value exist in aaa, and save it as a value_
test0<-scorecard%>%
  filter(cost<aaa)
_#now the logical comparison would work_
2. the other way to do this:
aaa <-scorecard%>%
  filter(!is.na(cost))
bbb<-aaa[aaa$name=="University of Chicago",]
aaa[aaa$cost<bbb$cost,]

**Comment by bensoltoff** [comment]
```r
aaa <- test1[[1]]
```

On my phone but I think this works. Need a way to retrieve the individual cell value for the 1x1 data frame. Will make more sense in a couple of weeks when we talk about vectors and sunsetting.

**Comment by WuyunpengChen** [comment]
Yes that works, I think it extracts the specific value at that location. I also figure out another way to solve this problem, I shall post it later as my computer is running out of battery.
