### ISSUE TITLE
Cannot Push to GitHub

### ISSUE THREAD

**Issue by EmilyForden** [uc-cfss/Discussion#4]
I have committed my changed locally in RStudio but when I attempt to push I receive the following error message:

remote: Permission to uc-cfss/hw01.git denied to EmilyForden.
fatal: unable to access 'https://github.com/uc-cfss/hw01.git/': The requested URL returned error: 403

A quick googling of GitHub error 403 says I either don't have permission to push or that the file name is incorrect. I believe the former is my problem but I don't know how to prove I have permission to push.

**Comment by bensoltoff** [comment]
You are trying to push to the original `hw01` repository, not your fork. You do not have permission to edit the original repository, only your forked version. When you clone the repo on your computer, make sure you use the link on your fork.

To fix this, you have two options:
1. Clone the correct repo from Github, move your changed files to that new repository, and commit and push from there. If you made multiple commits in your first repo, you won't preserve any of them. You'll only have the final version.
2. Change the url the computer is trying to use to push your changes to Github. Open your shell and use the `cd` (or `dir` if you use the command prompt on Windows) command to move to the directory on your computer where `hw01` is located. Then run the following commands

```
git remote -v
git remote set-url origin https://github.com/EmilyForden/hw01
git remote -v
```

The first command will tell you the current url you are pushing to (`'https://github.com/uc-cfss/hw01.git`, which is incorrect). The second will change that url to your forked version of the repository. Then the final command will let you check to make sure the change went through. If everything works, you can push in RStudio again and it should be successful.

**Comment by EmilyForden** [comment]
Since I am using a Mac, I have tried to re-do the assignment. I believe that I forked the homework this time (the name contains both hw1 and my name). I pasted in the code that I prepared, committed it, and pushed it. Now, when I push it, I receive a message that everything is up to date. I have tried to view my file on the HW1 repo, but it is only a few lines of code and doesn't look anything like the code I typed (or what it looks like on my preview button). I took a walk, shut everything down, and am trying again but nothing is improving.

**Comment by bensoltoff** [comment]
Make sure you stage the `readme.md` file. In RStudio, the upper right panel has a tab for Git. In order to make sure the file gets updated in GitHub, you need to check the box next to it before committing.

If you're still having issues, feel free to make an appointment with me or go to @jmausolf office hours on Tuesday.

**Comment by bagastiwo** [comment]
bullshit gais. 
abdullah nama ayahnya

**Comment by RanylFoumbi** [comment]
i have my repository 
but every time when i want to make a push  this error appear 
remote: **Permission to RanylFoumbi/Cassava-King.git denied to babayag.**
fatal: unable to access 'https://github.com/RanylFoumbi/Cassava-King.git/': The requested URL returned error: 403

please can you have a look on that .... until now if want to push i'm supposed to add  babayag as contributor while  it is my repository and i'm working alone
