### ISSUE TITLE
Topical example of linear regression

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#41]
@uc-cfss/fa17 [The Ultimate Halloween Candy Power Ranking](http://fivethirtyeight.com/features/the-ultimate-halloween-candy-power-ranking/) - from FiveThirtyEight. If they ever post the dataset to [their repo](https://github.com/fivethirtyeight/data), you could replicate their results in R. Alas, Walt Hickey is a Stata user.

**Comment by RCruzGil** [comment]
Thank you!
