### ISSUE TITLE
question about 2017-11-6's lecture

### ISSUE THREAD

**Issue by arthurzeyangyu** [uc-cfss/Discussion#42]
Dear all:

I'm pretty confused by this part's code (from indexes part to the end).

library(nycflights13)
copy_to(my_db,
        flights,
        temporary = FALSE,
        indexes = list(
          c("year", "month", "day"),
          "carrier",
          "tailnum"
        )
)

Can anyone explain this to me?

Best,
Arthur

**Comment by bensoltoff** [comment]
`indexes` creates indexes for the database. A [database index](https://en.wikipedia.org/wiki/Database_index) makes it more efficient to search through a database and retrieve rows. `indexes` defines which columns serve as indexes in the database

**Comment by arthurzeyangyu** [comment]
Thanks, Dr. Soltoff!
