### ISSUE TITLE
another question about 2017-11-6's lecture

### ISSUE THREAD

**Issue by arthurzeyangyu** [uc-cfss/Discussion#43]
Dear all:

I am confused by following codes:

library(broom)
(gap_nested <- gap_nested %>% 
  mutate(tidy = map(fit, tidy)))

In these codes, what does map(fit, tidy) do? What does tidy mean?

Best,
Arthur

**Comment by bensoltoff** [comment]
Look at the block of code before that. `fit` is a list-column in the data frame which contains a linear model for each country. So in this context, `map(fit, tidy)` maps the `tidy()` function from `broom` to each model in `fit`. Which when you `unnest()` the new `tidy` column, gives you one row for each coefficient for each country

**Comment by arthurzeyangyu** [comment]
Thanks for your answer, Dr. Soltoff!
