### ISSUE TITLE
question about multidplyr

### ISSUE THREAD

**Issue by arthurzeyangyu** [uc-cfss/Discussion#44]
Dear all:

I try to install the package: multidplyr, in my computer.

However, it shows that it's not available for R version 3.4.0.

How to deal with this problem?

Thanks,
Arthur

**Comment by bensoltoff** [comment]
[`multidplyr`](https://github.com/hadley/multidplyr) is not available on CRAN, so `install.packages("multidplyr")` will not work. Instead, you can install it directly from GitHub using `devtools::install_github("hadley/multidplyr")`

**Comment by arthurzeyangyu** [comment]
Thanks for your answer, Dr. Soltoff!
