### ISSUE TITLE
error with tidyverse

### ISSUE THREAD

**Issue by arthurzeyangyu** [uc-cfss/Discussion#47]
Dear Soltoff:

I have troubles using R.

After I download new packages in last week, I cannot use tidyverse function in R. Could you please explain why this happens?

Best,
Arthur

**Comment by bensoltoff** [comment]
How did you download the new packages? Are these new packages you installed, or did you update existing packages? Which packages are new? These are helpful details.

In general, when updating packages sometimes it breaks existing packages or causes conflicts. If you are having problems with `tidyverse` packages, try installing it again with `install.packages("tidyverse")` then loading it. Does this fix the problem?

**Comment by bensoltoff** [comment]
Also, what exactly is the error message? Is it related to [this](https://community.rstudio.com/t/tidyverse-update-problem/2613)?

**Comment by arthurzeyangyu** [comment]
Dear Dr. Soltoff:

Thanks for your quick response.

The error message is: library(tidyverse)
Error : .onAttach failed in attachNamespace() for ‘tidyverse’, details:
call: NULL
error: Function getThemeInfo not found in RStudio
Error: package or namespace load failed for ‘tidyverse’.

I also tried installing it again with install.packages("tidyverse") then loading it. This doesn't fix the problem.

:(

Best,
Arthur

**Comment by bensoltoff** [comment]
[See other possible solutions here](https://community.rstudio.com/t/tidyverse-package-v1-2-0-installation-loading-solutions/2697) Hopefully one of these should work

**Comment by arthurzeyangyu** [comment]
thanks! I will try this soon!
