### ISSUE TITLE
Problems with Knitting to PDF

### ISSUE THREAD

**Issue by nicholskl** [uc-cfss/Discussion#49]
Thanks for your help Dr. Soltoff. 

The issue is that I am unable to knit to a PDF because of the following error: 

pandoc.exe: Could not find data file templates\--highlight-style.latex

Error: pandoc document conversion failed with error 97
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Problem_Set_1_KN_Final.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Problem_Set_1_KN_Final.pdf --template  --highlight-style tango --latex-engine xelatex --variable graphics=yes --variable "geometry:margin=1in"' had status 97 

Execution halted

The only non-text substance I have in my RMD are the following two equations: 

$Y_m$ = $\beta_0$ + $\beta_1(Religiosity)$ + $\beta_2(Age)$ + $\beta_3(Ideological Orientation)$ + $$\beta_4(Age of Parents When Married)$ + $\beta_5(ParentsInLifeYesOrNo)$ +  
$\epsilon$ 

$$m = $$ $$\begin{cases}1\quad if & Y > 0\\0 \quad if & Y < 0 \end{cases}$$

and 

$$log(revenue) = $$ = $\beta_0$ + $\beta_1log(budget)$ + $\beta_2log(screens)$ + $\beta_3log(HSX)$ + 
$\epsilon$

However, even when I remove these from the RMD I get the same error. I have downloaded both MikTeK and Pandoc many times and have updated and restarted R to no avail.

**Comment by bensoltoff** [comment]
Stupid question, but have you tried restarting RStudio since the last time you installed MikTeX and Pandoc?

**Comment by bensoltoff** [comment]
I presume [this is the problem file](https://github.com/nicholskl/persp-model_W18/blob/master/Students/NicholsKristopher/Problem_Set_1_KN.Rmd). What if you remove `latex_engine: xelatex`? Just leave the front matter as

```
---
title: "Problem Set #1"
author: "Kristopher Nichols"
date: "January 8, 2018"
output: pdf_document
---
```

**Comment by nicholskl** [comment]
I have! The restart was not helpful.

It is! I just tried that and it did not work unfortunately. Continues to give me error 97.

**Comment by nicholskl** [comment]
And yes that is the problem file.

**Comment by bensoltoff** [comment]
I get an error rendering it on my computer. The problem is the equations, they are not properly formatted. The first equation should be

```
$$log(revenue) = \beta_0 + \beta_1 log(budget) + \beta_2 log(screens) + \beta_3 log(HSX) + \epsilon$$
```

And the second set of equations should be

```
$$Y_m = \beta_0 + \beta_1(Religiosity) + \beta_2(Age) + \beta_3(Ideological Orientation) + \beta_4(Age of Parents When Married) + \beta_5(ParentsInLifeYesOrNo) + \epsilon$$

$$m = \begin{cases}1\quad if & Y > 0\\0 \quad if & Y < 0 \end{cases}$$
```

Admittedly the second equation needs to wrap or it will go off the screen, however your attempt to make it wrap was not valid LaTeX code. You need to find a different way

**Comment by bensoltoff** [comment]
With those changes I was able to render it like [the attached file](https://github.com/uc-cfss/Discussion/files/1612997/test.pdf)

**Comment by nicholskl** [comment]
Sorry Dr. Soltoff but, even with those changes the file still did not knit correctly. I continue to get this error:

pandoc.exe: Could not find data file templates\--highlight-style.latex
Error: pandoc document conversion failed with error 97
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Problem_Set_1_KN_Final.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Problem_Set_1_KN_Final.pdf --template  --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 97 
Execution halted

**Comment by bensoltoff** [comment]
Hmm. That is quite confusing. Did you [update your LaTeX packages through MiKTeX?](https://miktex.org/howto/update-miktex) There might be a missing package that includes the `highlight-style.latex` file. If it is missing, then RMarkdown cannot finish rendering to PDF.

Also, did you render to HTML first to confirm it works? If so, you might just render to HTML then use your web browser to "print to pdf" or something similar. That way you can at least submit your homework assignment today.

**Comment by nicholskl** [comment]
That worked like a charm. I'll continue to troubleshoot, but thanks for the much needed help to at least get me by!
