### ISSUE TITLE
Question on the in-class problem 3

### ISSUE THREAD

**Issue by jtbeyond** [uc-cfss/Discussion#5]
To tidy the data of "experiment" (in-class problem 3), I write this code:

work<-activities  %>%
  select (id, trt, work.T1, work.T2) %>%
  gather (`work.T1`, `work.T2`, key="type", value="work")
work$type<-str_extract(work$type, "[1, 2]")

play<-activities  %>%
  select (id, trt, play.T1, play.T2) %>%
  gather (`play.T1`, `play.T2`, key="type", value="play")
play$type<-str_extract(play$type, "[1, 2]")

talk<-activities  %>%
  select (id, trt, talk.T1, talk.T2) %>%
  gather (`talk.T1`, `talk.T2`, key="type", value="talk")
talk$type<-str_extract(talk$type, "[1, 2]")

activities<-left_join(work,play) %>%
  left_join(talk)

It works, but it is very tedious. I was wondering to know the easier way to do this. Thank you.
@bensoltoff

**Comment by jtbeyond** [comment]
I think I have figured out this issue by using "unite" to combine the column with the similar tag, then "gather", then "separate". Am I correct?

**Comment by bensoltoff** [comment]
Your first solution is kludgy, but it works. That is, you do end up with a tidy data frame.

The most direct solution is actually a gather + separate + spread chain. See the [solution set](https://uc-cfss.github.io/extras/cm004_tidy_tutorial.html#activities) for more details.
