### ISSUE TITLE
DataCamp invitation

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#50]
@uc-cfss/sp18 

[DataCamp](https://www.datacamp.com/home) offers interactive R and Python courses on topics in data science, statistics, and machine learning. These are a supplement to our primary textbook and lessons. Introductory DataCamp courses are free, whereas premium courses generally cost a fee. As a participant in this course, you have free access to all premium courses for the duration of the term. Everyone currently on the roster was just sent an invitation email to create an account. There is no obligation, requirement, or expectation that you complete DataCamp modules. It is there for students who are interested in furthering their skills or reinforcing practice of basic programming principles.

**Comment by yeseulbyeon** [comment]
Hi, I signed up for the class during the second week of class, so I didn't receive a link for DataCamp courses. Would you re-send it to me at byeon@uchicago.edu?

**Comment by bensoltoff** [comment]
Done.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Benjamin Soltoff
209 McGiffert House
Lecturer in Computational Social Science
University of Chicago
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
