### ISSUE TITLE
Hw02

### ISSUE THREAD

**Issue by jvallee97** [uc-cfss/Discussion#53]
My homework two was running and I had graphs generated for all problems but the last problem. Then suddenly I have an error navigating the data.

In the first problem instead of getting the answer from the solutions (which is what I got orginally) I get this error

Error in count(gun_deaths, month) : object 'month' not found

Now none of my code is compiling. Not sure what to do.

**Comment by bensoltoff** [comment]
Is this occurring when you knit the document or you run the code chunks interactively? This would suggest that somewhere earlier in your code you accidentally deleted the `month` column in `gun_deaths`

**Comment by jvallee97** [comment]
It is occurring both times. This is happening on the very first problem, so it is the earliest I modified code. The only functions I used were count and kable (for the first problem) so do not see how I could have deleted the month column in gun-deaths. Also, when I run just gun_deaths the data loads and I can see the month column so it appears to be there.

**Comment by jvallee97** [comment]
I also went onto git and got an earlier version of my code where I know it was compiling/knitting correctly and still get the same error.

**Comment by bensoltoff** [comment]
I just cloned and knit your most recent commit on GitHub (from about 10 minutes ago). It works fine on my computer

**Comment by bensoltoff** [comment]
Try reinstalling `rcfss`. Run `devtools::install_github("uc-cfss/rcfss")` in your console, then knitting the document. Does that help?

**Comment by bensoltoff** [comment]
Pictures @jvallee97 sent me of his code and error message:

<img width="1280" alt="screen shot 2018-04-08 at 12 55 35 pm" src="https://user-images.githubusercontent.com/6217899/38470767-28196ec6-3b2d-11e8-880b-f90cc8c168d2.png">
<img width="1280" alt="screen shot 2018-04-08 at 12 56 33 pm" src="https://user-images.githubusercontent.com/6217899/38470768-28f8f820-3b2d-11e8-9b16-ba6297e77e0f.png">

**Comment by bensoltoff** [comment]
What is the output of `str(gun_deaths)` when you run that line of code in the console?

**Comment by bensoltoff** [comment]
Also, if you click the "Run" button there is an option to "Restart R and Clear Output". Do that, then try running the code chunks in the order they appear in the document.

**Comment by jvallee97** [comment]
The "restart R and clear output" fixed my issue. Thank you for your prompt response.
