### ISSUE TITLE
Suggestions for approach to last hw02 question?

### ISSUE THREAD

**Issue by estech01** [uc-cfss/Discussion#54]
Hi all,
I've been stuck on the last question of the homework for a little bit now. Although I am able to graph my data successfully with geom_box for the first comparison (police involvement vs. age), I am having a hard time reproducing the tables in the hw02 demo. 

Specifically, I am trying to use the group_by function, and when I try to group by age and count, I'm getting a weird result:

age = 0; n = 33
age = 1; n = 38
...
age = 107; n = 1

Any ideas what I may be doing wrong?

**Comment by nnickels** [comment]
Are you using group_by with age, and then using count? Just to clarify, can you show your code?

**Comment by estech01** [comment]
@nnickels Sure! I wasn't sure if we were allowed to show our code, which is why I didn't originally.

I have a new df named "police_involvement" which is the same as gun_deaths, except instead of [0,1] in the "police" column, I have "No Police Involvement" and "Police Involvement".

Here's my code:

group_by(police_involvement, police, age) %>%
  count() %>%
  kable(caption = "Average Age of Victim and Police Involvement",
        col.names = c("Police Involvement", "Age", "Deaths"))

My output table looks like: 

Police Involvement | Age | Deaths
-- | -- | --
No Police Involved | 0 | 33
No Police Involved | 1 | 38
No Police Involved | 10 | 53
No Police Involved | 100 | 1
No Police Involved | 101 | 2
etc.

I've reviewed my police_involvement$age column, and it's correct (i.e. no one is aged 0-11, or over 100). I tried converting the age column into strings in case that was the problem, and that didn't help either.

**Comment by nnickels** [comment]
Is the difference in your output table (when compared with the solution key) based on the fact that your kable is listing the "No Police Involved" deaths first, then the "Police Involved" deaths? I.e., when you look at your full table, are the Police Involved deaths listed after the No Police Involved deaths? It does seem like your output is listing the correct number of deaths for no police involved deaths in the data, if that makes sense.

**Comment by estech01** [comment]
@nnickels I'm not sure I understand your question.

In the solution key, the output table is:
police, age, n

Although I've renamed mine with the kable, it's still police, age, n.

If I filter to only look at "Police Involved" incidences, it does seem to be correct:
group_by(gun_deaths, police, age) %>%
  filter(police == "Police Involved") %>%
  count()

Output:

Police Inolvement | Age | Deaths
-- | -- | --
Police Involved | 12 | 1
Police Involved | 13 | 1
Police Involved | 14 | 1
Police Involved | 15 | 5
Police Involved | 16 | 7
Police Involved | 17 | 13



But why doesn't it work if I want to group by the police involvement, too?

**Comment by bensoltoff** [comment]
It does work, my `demo` solution just doesn't print all 172 rows of the table because that would be an absurdly large table.

Unfortunately, your results are correct. From 2012-14, 33 infants under the age of 1 year old were killed by guns. They just happened to not be involved in a police shooting. The youngest police involved shooting death was a 12 year old.

**Comment by nnickels** [comment]
Your table output may be listing the "No police involved" death counts by age before the "Police involved" death counts by age, but it is correct.

**Comment by estech01** [comment]
@bensoltoff Wow, that is extremely sad. You're right that when I use arrange(), I can see that there are 33 infant shootings with no police involvement, and one 12-year-old victim as the youngest police involved death.

@nnickels Thanks for your help with this! Still kind of wish I was wrong about the data, but here we are.
