### ISSUE TITLE
pushing hw2 to github

### ISSUE THREAD

**Issue by hibyeun** [uc-cfss/Discussion#55]
I believe I correctly cloned the repository and made new R project with it but as I was trying to turn my hw 2 in I got this message .. I'm not sure what to do.. 

<img width="650" alt="screen shot 2018-04-08 at 4 17 02 pm" src="https://user-images.githubusercontent.com/16866259/38472749-442f2b42-3b4a-11e8-80cb-4f9020ce7dd2.png">

**Comment by nnickels** [comment]
It looks like you were attempting to push to the master class repository (as opposed to your own forked repo), based on that Git Push message. Did you clone your own forked repository when you made a new R project initially?

**Comment by hibyeun** [comment]
I thought I did but it is possible that I might have accidentally cloned the master repository when I made the new project. So I retried just now to make a new project by cloning my own forked repository but now I got this message. 

<img width="1234" alt="screen shot 2018-04-08 at 4 52 42 pm" src="https://user-images.githubusercontent.com/16866259/38472956-60e6e484-3b4d-11e8-862e-9845c872b6de.png">

**Comment by nnickels** [comment]
Try creating a new, empty hw2 folder in the directory where you store your repositories, and cloning the forked repository into there when you open it as a new version control project in RStudio. Make sure the area you select on your computer (e.g. when RStudio offers "Create project as a subdirectory of:") isn't where a cloned repository is already stored.

**Comment by hibyeun** [comment]
It worked! I was able to submit my homework. Thank you so much for your help!
