### ISSUE TITLE
RMarkdown Reference

### ISSUE THREAD

**Issue by rcundiff** [uc-cfss/Discussion#56]
Hi all --

In perusing the interwebs, I found this really [helpful document on RMarkdown](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf).  Thought I'd share it with the class. :)

**Comment by bensoltoff** [comment]
@uc-cfss/sp18 this is also a reference guide from the same makers of your cheat sheets, just a more thorough documentation of R Markdown
