### ISSUE TITLE
How to evaluate hiv prevalence and count missing data

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#58]
Hi all, 

I review the table gapmind_hiv and do not see any "NA", so I wonder what could be regarded as "missing data". Also, should hiv rate be used to evaluate hiv prevalence?

Thanks

**Comment by bensoltoff** [comment]
Any rows for the gapminder data frame that do not have HIV info are missing. And yes, HIV rate is HIV prevalence.
