### ISSUE TITLE
Read.me & How to document the code

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#60]
I got the comment in this week that I should edit the read.me to make the code more clearly arranged, but I don't know what should be written in read.me. Also, I would like to know how to document the code. 

Thank you very much!

**Comment by bensoltoff** [comment]
For the `README.md` file, see [this](http://cfss.uchicago.edu/hw00_homework_guidelines.html#make_it_easy_for_people_to_access_your_work). For making the code more clearly arranged, we will talk more in class on Monday about coding style. If you look at the readings before then, that will give you some guidance beyond Gabe's original comments on your pull request.
