### ISSUE TITLE
What do we return for pythag thm?

### ISSUE THREAD

**Issue by jvallee97** [uc-cfss/Discussion#62]
"Write a function to calculate length of sides in a right-triangle using the Pythagorean Theorem"

Not sure what this means, I interpret it as given the length of the two legs a and b calculate the hypotenuse c.

**Comment by bensoltoff** [comment]
That is one possibility. What if I have the length of a and c and want to know b? Your function should be able to handle that scenario

**Comment by jvallee97** [comment]
Interesting, but for that to happen there would need to be a argument in the function specifying that one of the given side lengths is a hypotenuse otherwise you would be able to construct a triangle with a triangle equal to the square root of the sum of the squares given. So is that what you are looking for in this function? Given two sidelights and then a flag variable to say that one is a hypotenuse or not and then fine the missing side length?

**Comment by bensoltoff** [comment]
That is one approach that could work
