### ISSUE TITLE
how to draw a plot with two y-axises

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#65]
Hi all,

When I doing my project, for some data I need to draw a plot with to y-axises. I've searched online and only find the solution to draw two plots and combine these two. Is there any better way?

**Comment by bensoltoff** [comment]
Not using ggplot. It is considered bad to graph two separate y axes as it can make it appear as if two trends are correlated even if in truth they are not. You're better off drawing two separate plots or a scatterplot if you want to compare variables directly
