### ISSUE TITLE
lowest mse

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#67]
I am wondering if we use lm() we will get the slope and intercept with lowest mse. Do we have to calculate it separately?

**Comment by bensoltoff** [comment]
`lm()` will provide the most accurate slope and intercept given the variables specified in the model. The MSE of that model may or may not be lower than the MSE of a different `lm()` model with a different set of variables. So yes, you still need to estimate the MSE separately to compare across models.
