### ISSUE TITLE
Nora's Office Hours: 5/8 and 5/15

### ISSUE THREAD

**Issue by nnickels** [uc-cfss/Discussion#68]
@uc-cfss/sp18 
My OH are usually Tuesdays from 12 PM - 2 PM, but I have a few small changes with my office hours for this week and next:
Tuesday, May 7th: 11:00 AM - 1:00 PM
Tuesday, May 15th: 11:00 AM - 12:00 PM, 1:00 PM - 2:00PM
I am also available by appointment as well if these changes create conflicts for you!
Thanks!
- Nora

**Comment by estech01** [comment]
Dear Nora,
Would it be possible to troubleshoot my Java issue (preventing me from
running spark/lyr) at some point tomorrow? I have an unmovable appt.
(doctor) at 3:30, so I'm worried I may not resolve the problem in Lab.

Unfortunately, I had class during your office hours today, or else I
would've come in.

Please let me know!
Elayne

**Comment by bensoltoff** [comment]
@estech01 I have office hours on Thursday 1-3pm and Chelsea Friday 9:30-11:30. Any of us should be able to help you.

**Comment by estech01** [comment]
@bensoltoff I have a midterm right at 1:30 on Thursday in Harris, do you think 1:00 - 1:15 would be long enough to resolve the issue? Could I possible sneak in a bit early (say, 12:45)?

**Comment by bensoltoff** [comment]
@estech01 possibly but it is not guaranteed. I might be in the office prior to 1, but we have the Computation workshop before my office hours - I don't know exactly when I will be back.

**Comment by estech01** [comment]
@bensoltoff do you think 15 minutes (1-1:15) would be sufficient? I unfortunately have a job interview on Friday morning, so I don't think I make it to Chelsea's office hours.

In terms of trying to trouble-shoot this myself, I downloaded a legacy version of Java and subsequently, the most recent one, based on stack over flow suggestions. Neither solution fixed the error, unfortunately.

**Comment by nnickels** [comment]
@estech01 Can you post the current error message here, as well? If we run into it in lab tomorrow helping other people with their errors, perhaps we'll be able to help you solve it based on what we figure out in lab.

**Comment by estech01** [comment]
@nnickels 
The error I have now is:
`Error in validate_java_version_line(master, version) : Java version1.6.0.65 detected but 1.7+ is required. Please download and install Java from https://www.java.com/en/`

I have since installed Java from the link (and restarted both RStudio and my computer) and am still getting this error. Previously, it was a more general Java error (not about the version I had, but just Java not running properly).

**Comment by bensoltoff** [comment]
Try the solution I just posted in #71. It may lead you to the correct version of Java.

**Comment by estech01** [comment]
@bensoltoff installed homebrew and ran the code, got this:
`Error: Cask 'java' is not installed.`
Does this mean it worked, or is this part of the problem?

**Comment by bensoltoff** [comment]
Might be part of the problem. Skip to the next step to install Java8. Then try the `sparklyr` code

**Comment by estech01** [comment]
@bensoltoff seems to be working now (?) after Java 8 install:
`library(sparklyr)
sc <- spark_connect(master = "local")`

`* Using Spark: 2.1.0`

**Comment by bensoltoff** [comment]
Great to hear!
