### ISSUE TITLE
trying to aggregate count for not high school

### ISSUE THREAD

**Issue by carlyoffidani** [uc-cfss/Discussion#7]
Hey all, 

I've been trying to figure out how to summarise deaths by everyone who has a HS degree or higher. I'm fine filtering, and I was able to count by each discrete level of education, but I'm trying to figure out how to add up all the deaths, except for those with less than HS. all my codes for not highschool (ie -"Less than HS" or !"Less than HS" aren't working.. 

gun_deaths %>%
  filter(sex == "M") %>%
  filter(race == "White") %>%
  filter(year == "2012") %>%
    summarise(education, -"Less than HS")

**Comment by bensoltoff** [comment]
The expression for checking if two values are not equivalent is `!=`. You can use this in a `filter()` function.
