### ISSUE TITLE
scales in ggplot2

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#70]
I tried to change the scales of my plots using scale_x_discrete as follows, but then the total scales of axises disappear:

ggplot(data = Biden_survey, aes(x = female, y = biden)) +
  geom_boxplot(mapping = aes(group = female)) +
 scale_x_discrete(breaks = c("0.0", "1.0"), labels = c("Male", "Female")) +
labs(
    title = "Relation between Gender and Ratings for Biden",
    x = "Gender",
    y = "Ratings for Biden"
  )

 I wonder how to deal with that.

**Comment by bensoltoff** [comment]
Should `breaks = c("0.0", "1.0")` instead be `breaks = c(0.0, 1.0)`?

**Comment by jingyi22** [comment]
I tried, but it still doesn't work.
