### ISSUE TITLE
Java errors with sparklyr? Look here

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#71]
@uc-cfss/sp18 Here's a solution from the fall that worked for many people - maybe it will work for you (h/t to @cernhofer for the original solution).

---------

If you're getting errors that look like this:

> Using Spark: 2.1.0
    Error in validate_java_version_line(master, version) : 
    Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.

Or like this:

> Error in force(code) : Failed while connecting to sparklyr to port (8880) for sessionid (7199): Gateway in port (8880) did not respond. Path: C:\Users\HP\AppData\Local\rstudio\spark\Cache\spark-2.0.0-bin-hadoop2.7\bin\spark-submit2.cmd Parameters: --class, sparklyr.Backend, "C:\Users\HP\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 7199 ---- Output Log ---- '"java"' is not recognized as an internal or external command, operable program or batch file. ---- Error Log ----

If this occurs, you may need to uninstall Java 9 and install Java 8 on your computer. This worked for a few students in the fall with these types of errors.

Here's how you do it:
1.  Uninstall Java9 
    * Go to your terminal and enter the following `brew cask uninstall java`
    * If you do not have Homebrew installed on your computer, [go here to get installation instructions](https://brew.sh/).
1. Install Java8 
     - [Go here.](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html?printOnly=1) Scroll or find the block for **Java SE Development Kit 8u151**.
     - Click the button that you accept the licence agreement and download the option that fits with your machine (e.g. Windows, MacOS).
     - Once it's downloaded click on it and follow the download instructions.

That should work! Because you need an older version of Java, you cannot use Homebrew to install the correct version.

If this doesn't work for you open a new issue with specifics about the error message you are getting and we can try to troubleshoot it online, or stay for lab tomorrow.

**Comment by nnickels** [comment]
If you are using the above issue to solve Java-related errors with using spark, and have successfully installed Homebrew and uninstalled Java 9, you can use the following code to download Java 8 without logging into Oracle (aka downloading directly from terminal):
```
brew tap caskroom/versions
brew cask install java8
```
This should work to successfully install Java 8; restart your R session and try working with spark again.

**Comment by ThomasYan1987** [comment]
Hello bensoltoff,

I follow the above instruction. But i still get the error message (see below). How can I deal with it? Could you please help? Thanks!

> library(sparklyr)
> sc <- spark_connect(master = "local")
* Using Spark: 2.3.0
Error in validate_java_version_line(master, version) : 
  Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.

Regards,
Thomas

**Comment by wustream** [comment]
Thanks!

`brew tap caskroom/versions`
`brew cask install java8`
Works perfectly for me after I followed the instructions below to uninstall my the java first. 
https://www.java.com/en/download/help/mac_uninstall_java.xml
