### ISSUE TITLE
Choropleth

### ISSUE THREAD

**Issue by jvallee97** [uc-cfss/Discussion#73]
I have a map of Oregon where I map the weather stations in it showing the counties. What I want to do is make a choropleth of population in Oregon by county. Right now I have one of the continental U.S by county and state but do not know how to limit it to just Oregon. All my code is committed on Git. THe data for population is taken from Lecture notes.

**Comment by jvallee97** [comment]
![image](https://user-images.githubusercontent.com/37882418/40001237-680c4f84-5753-11e8-9e94-124e8ab3c17e.png)

**Comment by jvallee97** [comment]
That picture is what it currently looks like, I just want it to be a picture of oregon. Here is the codeusa <- readOGR("cb_2013_us_state_20m/cb_2013_us_state_20m.shp")

usa2 <- usa %>%
  fortify(region = "GEOID") %>%
  as_tibble() %>%
  left_join(usa@data, by = c("id" = "GEOID")) %>%
  # filter out Alaska, Hawaii, Puerto Rico via FIPS codes
  filter(!(STATEFP %in% c("02", "15", "72")))


counties <- readOGR("cb_2013_us_county_20m/cb_2013_us_county_20m.shp")

counties2 <- counties %>%
  fortify(region = "GEOID") %>%
  as_tibble() %>%
  left_join(counties@data, by = c("id" = "GEOID")) %>%
  # filter out Alaska, Hawaii, Puerto Rico via FIPS codes
  filter(!(STATEFP %in% c("02", "15", "72")))

counties2
```

```{r}
(fb_state <- read_csv("ACS_13_5YR_B05012.csv") %>%
  mutate(rate = HD01_VD01))

(fb_county <- read_csv("ACS_13_5YR_B050122.csv") %>%
  mutate(rate =  HD01_VD01))

fb_county %>%
  mutate(rate_cut = cut_number(rate, 6)) %>%
  ggplot(aes(map_id = GEO.id2)) +
  geom_map(aes(fill = rate_cut), map = counties2) +
  expand_limits(x = counties2$long, y = counties2$lat) +
  labs(title = "Rate of foreign-born individuals in the population",
       fill = NULL) +
  ggthemes::theme_map() +
  coord_map(projection = "albers", lat0 = 25, lat1 = 50)

**Comment by bensoltoff** [comment]
You need either a shapefiles for just Oregon counties or you need to filter the shapefiles just to include county observations from Oregon. I don't recall off hand how to filter a shapefiles in R.

**Comment by bensoltoff** [comment]
Instead of `filter(!(STATEFP %in% c("02", "15", "72"))`, write the filter to only keep observations which match Oregon's FIPS code. You should be able to find that online easily

**Comment by jvallee97** [comment]
When I look online on how to filter shapefiles I get things using maptools library. Are we allowed to use that library?

**Comment by bensoltoff** [comment]
You can but after you `fortify` the shapefiles you have a standard data frame. So all you need is the `filter()` function. You know how to filter data frames
