### ISSUE TITLE
Graduating students and final grades

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#75]
@uc-cfss/sp18 If you are graduating this term, pay attention to the following information:

The final homework assignment is due the Monday of exam week. Final grades for graduating students are due by Friday of the tenth week.

## If you are a master's or PhD student

* By Friday of tenth week, I will submit a tentative grade to the registrar based on your first nine assignments.
* I will update that grade after the final homework assignment has been collected and evaluated during exam week. As long as this grade does not result in you failing the class (which at this point no student is in danger of that outcome), this will not change your graduation status.

## If you are an undergraduate student

* I will make the `hw10` repo accessible starting Monday of tenth week. You will need to read in advance the notes and exercises we will be completing in class that Wednesday. You must submit your homework assignment by **5pm Thursday of tenth week** via pull request. I won't expect peer evaluations from you that week.
* Myself and the TAs will evaluate your final homework assignment by the grade submission deadline on Friday. I will submit your final grade to the registrar by the deadline so you will be able to graduate on-time.

If any student has a question about this procedure, post a reply to this issue.

**Comment by sumervaid** [comment]
Hi Professor,
As a joint-program student (BA/MA), am I to follow homework procedures for master's/PhD students or the undergraduate students? I am taking the class as a master's student currently, but I am enrolled both as an undergrad and a grad because of the joint program.

**Comment by bensoltoff** [comment]
To be safe, submit your final assignment at the undergrad deadline
