### ISSUE TITLE
errors in searching tweets & .Rprofile

### ISSUE THREAD

**Issue by jingyi22** [uc-cfss/Discussion#76]
I tried `create_token` to create a token for searching tweets but it returns a error message of "Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, : Forbidden (HTTP 403)." 
[Then I tried this method](https://stackoverflow.com/questions/29504484/twitter-package-for-r-authentication-error-401), and I successfully see the rds file. But when I perform the function `search_tweets`, it returns "Error in readRDS(pat) : error reading from connection". I can't figure out why.

Also, I can't find where is my .Rprofile. Is it automatically created or do I have to create by myself?

**Comment by bensoltoff** [comment]
You create your own `.Rprofile` in your repo. The second method you tried I was mistaken about - it works for the `twitteR` package, not `rtweet`.

It may work to not even provide your own app information. `rtweet` contains a default Twitter developer app you may be able to use instead. Try running the search function without creating a token first.

**Comment by raionas** [comment]
I'm having a similar issue here when running search_tweets function @bensoltoff 

rstats <- search_tweets("#rstats", n=300)

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bit’

I tried installing the dependencies but still no luck. Any help would be great.

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.6.0

**Comment by bensoltoff** [comment]
What happens if you `install.packages("bit")`?

**Comment by raionas** [comment]
@bensoltoff it **worked** like a charm! thank you!
