### ISSUE TITLE
Error with spark_connect()

### ISSUE THREAD

**Issue by ThomasYan1987** [uc-cfss/Discussion#78]
Hello,

I follow the above instruction of #71 . But i still get the error message (see below). How can I deal with it? Could you please help? Thanks!

library(sparklyr)
sc <- spark_connect(master = "local")
Using Spark: 2.3.0
Error in validate_java_version_line(master, version) :
Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.

Regards,
Thomas

**Comment by bensoltoff** [comment]
DId you uninstall Java 9 successfully? Restart your machine after uninstalling it? The error suggests you still have Java 9 on your computer, while Spark and `sparklyr` need Java 8. [Here is a guide for MacOS](http://osxdaily.com/2017/06/16/uninstall-java-mac/). If you're on Windows or Linux you'll need to find alternative instructions.

**Comment by ThomasYan1987** [comment]
Actually, I follow the same instruction as that you shared to uninstall Java 9. I try again. It still doesn't work!
