### ISSUE TITLE
Issue separating column while tidying data

### ISSUE THREAD

**Issue by spcoyne** [uc-cfss/Discussion#8]
I'm trying to tidy the data in the dadmom data set. My plan of attack was to create transformed  variables so that the name would be associated with the salary into one cell, then gather those transformed columns into a single column, which I could then separate and drop the other unnecessary columns. This is the code I have and it works until I try to separate my transformed column: 

dadmom
tidy_list1 <- dadmom %>%
  transform(dad = paste(named,incd)) %>%
  transform(mom = paste(namem,incm))
tidy_list1

tidy_list1[2:5] <- list(NULL)

gather(tidy_list1, key = family_info, value = name_sal, -famid) 
# works through this line of code

separate(tidy_list1, name_sal, into = c("par_name", "par_sal"))
# once I try this line of code, I get the following error message:

Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  argument is of length zero

**Comment by bensoltoff** [comment]
Remember: `tidyverse` functions such as `gather()` never replace existing objects unless you explicitly tell it to do so. Because of this, the gathered `tidy_list1` is never saved, so `separate()` tries to modify tidy_list1 pre-gather. Use the pipe to connect the two functions:

``` r
dadmom
tidy_list1 <- dadmom %>%
  transform(dad = paste(named,incd)) %>%
  transform(mom = paste(namem,incm))
tidy_list1

tidy_list1[2:5] <- list(NULL)

gather(tidy_list1, key = family_info, value = name_sal, -famid) %>%
  separate(name_sal, into = c("par_name", "par_sal"))
```
