### ISSUE TITLE
Class canceled tomorrow October 29

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/Discussion#80]
@uc-cfss/fa18 As a reminder, we will not have class tomorrow October 29. We will cover cm009 material on Wednesday and I will determine how to best facilitate cm010 at a later time. hw04 is still due tomorrow by 1:30pm. Students who have serious issues attempting to finish the assignment on time can wait to submit until Wednesday without penalty. I will have make-up office hours on Wednesday from 11-12.

**Comment by teylorw** [comment]
Hi Benjamin,

I’m still having some trouble getting the iteration function to work to
import the data. I could really use some help at your office hours or with
the TA’s. Would I be able to turn the assignment in Wednesday before class?
Thanks!

**Comment by bensoltoff** [comment]
@teylorw yes
