### ISSUE TITLE
How to tackle question 6 in part three of the HM?

### ISSUE THREAD

**Issue by HebaAlex** [uc-cfss/Discussion#86]
Hello, 
I don't know how to answer question 6, part 3. Any recommendation on how to begin? Thanks

**Comment by bensoltoff** [comment]
1. Filter the data frame so you only keep cases that were decided after oral arguments. `decisionType` is going to help you here. Read [the documentation](http://scdb.wustl.edu/documentation.php?var=decisionType) to understand how the variable is encoded.
1. Filter the data frame so it is one row per case
1. Identify the month in which each case is decided. This can be extracted from the `dateDecision` variable. `lubridate` is a good package for working with date columns and is discussed in [R4DS](https://r4ds.had.co.nz/dates-and-times.html).
1. Count the number of decisions published in each term in each month.
1. Generate a boxplot to visualize the distribution of the monthly number of published decisions across terms.
