### ISSUE TITLE
Can't generate boxplot for Question #6 

### ISSUE THREAD

**Issue by kangkanak** [uc-cfss/Discussion#87]
I've been working on Question 6 for a while now but no matter what I do I can't seem to get my boxplot right. Comparing my boxplot and the boxplot in the solution it looks like for my number of issues (x axis) it goes up to 500 and in the solution it goes up to 80. I looked at the previous instructions for the issue someone else opened for #6 and tried to follow them however, I still had no luck. I feel like I might be misunderstanding how to filter the data frame. This is the code I've been running. 

DecisionDates <- scdbv %>% 
  separate(col = dateDecision, into = c("dmonth", "day", "year"), sep = "/") %>% 
  mutate(dmonth = factor(dmonth, labels = month.abb))

OralDecision <- DecisionDates %>% 
  select(term, dmonth, day, year, dateArgument, decisionType) %>% 
  filter(decisionType == 1 | decisionType == 6 | decisionType == 7) %>% 
  mutate(oralarg = ifelse(is.na(dateArgument) == 1, 0, 1)) %>% 
  filter(oralarg == 1)

Decisioncount <- OralDecision %>% 
count(term, dmonth)

ggplot(Decisioncount, aes(n, dmonth)) +
  geom_boxplot()

**Comment by kangkanak** [comment]
I think I figured out why the numbers were different, by adding this line of code after my filter I've made one row per case and my new dataframe is now correct(maybe) but the box plot still isn't showing up correctly.  

distinct(docketId, .keep_all = TRUE)

**Comment by bensoltoff** [comment]
What do you mean it isn't correct?

**Comment by kangkanak** [comment]
This is what my boxplot comes out at 

![Screen Shot 2019-04-21 at 6 18 56 PM](https://user-images.githubusercontent.com/49250445/56476711-fe25b480-6461-11e9-96d0-857ad590dffa.png)

**Comment by bensoltoff** [comment]
But what is wrong with it? Is the data being visualized incorrect, or do
you want to modify the appearance of the graph?

**Comment by kangkanak** [comment]
The data is being visualized incorrectly I believe. When I compare it against your solution example for the question the numbers are very different. I think I'm having a problem with how I'm inputting the arguments into ggplot? Or maybe how I'm making the count data frame which I used in the ggplot?

**Comment by bensoltoff** [comment]
Remove

```r
mutate(oralarg = ifelse(is.na(dateArgument) == 1, 0, 1)) %>%
filter(oralarg == 1)
```

You don't need to calculate an oral argument variable. Filtering on decisionType already accounts for that

**Comment by bensoltoff** [comment]
Also you're better off using a function from the `lubridate` package to extract the month variable. See the assignment instructions for that exercise.

**Comment by kangkanak** [comment]
I already removed that part and tried it earlier it was the same. As for extracting the months variable, do you think that's the problem and not the way I'm structuring my ggplot? I thought the way I separated the months with my code was fine, but if that's what's causing the incorrect data visualization I'll try it out!

**Comment by bensoltoff** [comment]
`geom_boxplot()` does a simple frequency count to transform the input data frame. You shouldn't have to mess with anything there. My guess is that the problem lies in how the data frame is calculated.
